/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsPredictor : NSObject <MapsSuggestionsPredictor> {
    NSObject<OS_dispatch_source> * _closeTimer;
    NSXPCConnection * _connection;
    NSObject<OS_dispatch_queue> * _queue;
    MapsSuggestionsSignalPackCache * _signalPackCache;
    int  _tempPredictedTransportMode;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSString *uniqueName;

+ (id)sharedPredictor;

- (void).cxx_destruct;
- (void)_closeConnection;
- (void)_initCloseTimerIfNecessary;
- (bool)_openConnectionIfNecessary;
- (void)_scheduleCloseConnection;
- (void)_unscheduleCloseConnection;
- (void)cancelCapturingAnalytics;
- (void)captureActualTransportationMode:(int)arg1 originMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg2 destinationMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg3;
- (void)capturePredictedTransportationMode:(int)arg1;
- (void)dealloc;
- (id)init;
- (bool)predictedTransportModeForDestinationEntry:(id)arg1 originCoordinate:(struct CLLocationCoordinate2D { double x1; double x2; })arg2 handler:(id /* block */)arg3;
- (bool)predictedTransportModeForDestinationMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg1 originCoordinate:(struct CLLocationCoordinate2D { double x1; double x2; })arg2 handler:(id /* block */)arg3;
- (void)storeSignalPack:(id)arg1 forMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg2;
- (struct NSString { Class x1; }*)uniqueName;

@end
