/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsMSPSource : MapsSuggestionsBaseSource <MapsSuggestionsSource> {
    MapsSuggestionsCanKicker * _canKickerFavoriteNotification;
    MapsSuggestionsCanKicker * _canKickerHistoryNotification;
    MSPFavoritesContainer * _favoritesContainer;
    bool  _favoritesEnabled;
    struct NSMutableArray { Class x1; } * _favoritesEntriesToAdd;
    MSPHistoryContainer * _historyContainer;
    int  _notificationTokenForFavorites;
    int  _notificationTokenForRecentHistory;
    bool  _notificationsRegistered;
    NSObject<OS_dispatch_queue> * _queue;
    struct NSMutableArray { Class x1; } * _recentsEntriesToAdd;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MapsSuggestionsSourceDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSString *uniqueName;

+ (unsigned long long)disposition;
+ (bool)isEnabled;

- (void).cxx_destruct;
- (bool)_addFieldsToSuggestionsEntry:(id)arg1;
- (id)_createEntryFromFavoritePlace:(id)arg1;
- (id)_createEntryFromRecentHistoryPlaceDisplay:(id)arg1;
- (id)_createEntryFromRecentHistoryRoute:(id)arg1;
- (id)_extractTitleAndSubtitleFromMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg1;
- (struct NSArray { Class x1; }*)_mergeRecentsAndFavoritesList;
- (void)_registerNotification;
- (bool)_removeEntry:(id)arg1 behavior:(long long)arg2 handler:(id /* block */)arg3;
- (void)_unregisterNotification;
- (void)_updateFavoritesEntries;
- (void)_updateRecentHistoryEntries;
- (bool)canProduceEntriesOfType:(long long)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (bool)removeEntry:(id)arg1 behavior:(long long)arg2 handler:(id /* block */)arg3;
- (void)start;
- (void)stop;
- (double)updateSuggestionEntries;

@end
