/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsShortcut : NSObject <NSCopying, NSSecureCoding> {
    NSArray * _contacts;
    NSString * _customName;
    struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; } * _geoMapItem;
    NSString * _identifier;
    bool  _isHidden;
    NSString * _originatingAddressString;
    NSUUID * _storageIdentifier;
    long long  _type;
}

@property (nonatomic, copy) NSArray *contacts;
@property (nonatomic, copy) NSString *customName;
@property (nonatomic, copy) GEOMapItemStorage *geoMapItem;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, readonly) bool isBackedPlaceholder;
@property (nonatomic) bool isHidden;
@property (nonatomic, readonly) bool isSetupPlaceholder;
@property (nonatomic, copy) NSString *originatingAddressString;
@property (nonatomic, copy) NSUUID *storageIdentifier;
@property (nonatomic, readonly, copy) NSString *subtitle;
@property (nonatomic, readonly, copy) NSString *title;
@property (nonatomic) long long type;

+ (id)shortcutWithData:(id)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (bool)_isPlaceholder;
- (id)_name;
- (id)_originalName;
- (void)addContact:(id)arg1;
- (id)contacts;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)customName;
- (id)data;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)geoMapItem;
- (id)identifier;
- (id)initBackedPlaceholderWithType:(long long)arg1 identifier:(id)arg2 customName:(id)arg3;
- (id)initBackedPlaceholderWithType:(long long)arg1 identifier:(id)arg2 originatingAddress:(id)arg3 customName:(id)arg4;
- (id)initSetupPlaceholderOfType:(long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithGEOMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg1 customName:(id)arg2;
- (id)initWithPinnedPlace:(id)arg1;
- (id)initWithType:(long long)arg1 geoMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg2 customName:(id)arg3;
- (id)initWithType:(long long)arg1 identifier:(id)arg2 geoMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg3 customName:(id)arg4;
- (id)initWithType:(long long)arg1 identifier:(id)arg2 geoMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg3 customName:(id)arg4 contacts:(id)arg5 isHidden:(bool)arg6 originatingAddress:(id)arg7;
- (bool)isBackedPlaceholder;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToPinnedPlace:(id)arg1;
- (bool)isEqualToShortcut:(id)arg1;
- (bool)isHidden;
- (bool)isSetupPlaceholder;
- (id)originatingAddressString;
- (int)pinnedStorageType;
- (void)removeContact:(id)arg1;
- (void)setContacts:(id)arg1;
- (void)setCustomName:(id)arg1;
- (void)setGeoMapItem:(struct GEOMapItemStorage { Class x1; id x2; id x3; id x4; id x5; id x6; unsigned int x7; unsigned int x8; struct os_unfair_lock_s { unsigned int x_9_1_1; } x9; struct { unsigned int x_10_1_1 : 1; unsigned int x_10_1_2 : 1; unsigned int x_10_1_3 : 1; unsigned int x_10_1_4 : 1; unsigned int x_10_1_5 : 1; unsigned int x_10_1_6 : 1; unsigned int x_10_1_7 : 1; unsigned int x_10_1_8 : 1; unsigned int x_10_1_9 : 1; unsigned int x_10_1_10 : 1; unsigned int x_10_1_11 : 1; unsigned int x_10_1_12 : 1; unsigned int x_10_1_13 : 1; unsigned int x_10_1_14 : 1; unsigned int x_10_1_15 : 1; unsigned int x_10_1_16 : 1; unsigned int x_10_1_17 : 1; unsigned int x_10_1_18 : 1; } x10; }*)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setIsHidden:(bool)arg1;
- (void)setOriginatingAddressString:(id)arg1;
- (void)setStorageIdentifier:(id)arg1;
- (void)setType:(long long)arg1;
- (id)storageIdentifier;
- (id)subtitle;
- (id)title;
- (long long)type;

@end
