/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKNotificationObserver : NSObject {
    NSObject<OS_dispatch_source> * _memoryNotificationEventSource;
    SEL  _selector;
    struct _geo_weak_ptr<id<VKNotificationObserverDelegate> > { 
        <VKNotificationObserverDelegate> *_p; 
    }  _target;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_receivedFlushTileCachesNotification;
- (void)_receivedLocalChangedNotification;
- (void)_receivedMemoryNotification;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 taskContext:(const struct TaskContext { id x1; /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x2; in int x3; long long x4; void*x5; void*x6; void*x7; void*x8; void*x9; const void*x10; void*x11; void*x12; out SEL x13; SEL x14; void*x15; void*x16; short x17; void*x18; unsigned long long x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; short x26; void*x27; double x28; SEL x29; SEL x30; void*x31; void*x32; void*x33; SEL x34; SEL x35; double x36; void*x37; float x38; void*x39; void*x40; long x41; void*x42; void*x43; double x44; void*x45; long x46; void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; out SEL x53; SEL x54; void*x55; void*x56; short x57; void*x58; unsigned long long x59; void*x60; void*x61; void*x62; void*x63; void*x64; void*x65; void*x66; void*x67; struct __compressed_pair<geo::TaskQueue *, std::__1::default_delete<geo::TaskQueue> > { struct TaskQueue {} *x_68_1_1; } x68; }*)arg2;

@end
