/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKRouteLineObserver : NSObject <VKRouteLineObserverProtocol> {
    VKRouteLine * _routeLine;
    struct LabelTransitSupport { int (**x1)(); int (**x2)(); struct LabelManager {} *x3; struct shared_ptr<md::DataOverrideManager> { struct DataOverrideManager {} *x_4_1_1; struct __shared_weak_count {} *x_4_1_2; } x4; struct _retain_ptr<VKRouteContext *, geo::_retain_objc, geo::_release_objc, geo::_hash_objc, geo::_equal_objc> { int (**x_5_1_1)(); id x_5_1_2; /* Warning: Unrecognized filer type: '_' using 'void*' */ void*x_5_1_3; const void*x_5_1_4; void*x_5_1_5; void*x_5_1_6; int x_5_1_7; in void*x_5_1_8; out unsigned int x_5_1_9/* : ? */; void*x_5_1_10; BOOL x_5_1_11; void*x_5_1_12; } x5; struct _release_objc { } x6; } * _transitSupport;
}

- (void)dealloc;
- (id)initWithTransitSupport:(struct LabelTransitSupport { int (**x1)(); int (**x2)(); struct LabelManager {} *x3; struct shared_ptr<md::DataOverrideManager> { struct DataOverrideManager {} *x_4_1_1; struct __shared_weak_count {} *x_4_1_2; } x4; struct _retain_ptr<VKRouteContext *, geo::_retain_objc, geo::_release_objc, geo::_hash_objc, geo::_equal_objc> { int (**x_5_1_1)(); id x_5_1_2; /* Warning: Unrecognized filer type: '_' using 'void*' */ void*x_5_1_3; const void*x_5_1_4; void*x_5_1_5; void*x_5_1_6; int x_5_1_7; in void*x_5_1_8; out unsigned int x_5_1_9/* : ? */; void*x_5_1_10; BOOL x_5_1_11; void*x_5_1_12; } x5; struct _release_objc { } x6; }*)arg1 andRouteLine:(id)arg2;
- (void)routeLineDidUpdateSections:(id)arg1;

@end
