/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreServicesStore.framework/CoreServicesStore
 */

@interface _CSStore : NSObject <NSSecureCoding> {
    NSObject<OS_dispatch_queue> * _accessQueue;
    /* Warning: unhandled struct encoding: '{Store="dataContainer"@"tableOffsets"{array<unsigned int, 64>="__elems_"[64I]}"arrayTable"^{Table}"stringTable"^{Table}"enumerationState"{atomic<long long>="__a_"Aq}"getNSDataCallCount"{atomic<long long>="__a_"Aq}"pedigree"{Pedigree="family"Q"generationAtCopyTime"{optional<unsigned int>=""(?="__null_state_"c"__val_"I)"__engaged_"B}}}' */ struct Store { 
        id dataContainer; 
    }  _store;
}

+ (void)initialize;
+ (id)new;
+ (bool)supportsSecureCoding;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initByMovingStore:(struct Store { id x1; /* Warning: Unrecognized filer type: 'a' using 'void*' */ void*x2; const const void*x3; void*x4; void*x5; void*x6; in short x7; int x8; void*x9; in void*x10; double x11; void*x12; int x13; in void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; unsigned int x21[64]; }*)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 error:(id*)arg2;
- (id)initWithError:(id*)arg1;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1 error:(id*)arg2;
- (void)setExpectedAccessQueue:(id)arg1;

@end
