/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface _ASKResourceCacheGroup : NSObject {
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _guard;
    bool  _hasMultipleMembers;
    NSMutableArray * _memberContents;
}

@property bool hasMultipleMembers;

- (void).cxx_destruct;
- (void)discardMemberContents:(struct NSCache { Class x1; id x2; /* Warning: Unrecognized filer type: '5' using 'void*' */ void*x3; void *x4; void*x5; void *x6; }*)arg1;
- (bool)hasMultipleMembers;
- (id)init;
- (struct NSCache { Class x1; id x2; /* Warning: Unrecognized filer type: '5' using 'void*' */ void*x3; void *x4; void*x5; void *x6; }*)makeMemberContents;
- (struct NSCache { Class x1; id x2; /* Warning: Unrecognized filer type: '5' using 'void*' */ void*x3; void *x4; void*x5; void *x6; }*)onlyMemberContents;
- (void)setHasMultipleMembers:(bool)arg1;
- (id)snapshotMemberContents;

@end
