/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface SFDownloadsBarButtonItemView : UIView <CAStateControllerDelegate, SFDeferrableUpdateView> {
    UIButton * _innerButton;
    UIBarButtonItem * _item;
    double  _progress;
    UIProgressView * _progressView;
    CAStateController * _stateController;
    /* Warning: unhandled struct encoding: '{?="foregroundNotificationObserver"@"backgroundNotificationObserver"@"needsDeferredContentUpdate"B"sceneIsForeground"B}' */ struct { 
        id foregroundNotificationObserver; 
    }  deferrableUpdateViewState;
}

- (void).cxx_destruct;
- (void)_buttonPressed;
- (void)_dynamicUserInterfaceTraitDidChange;
- (struct { id x1; bool x2; bool x3; }*)deferrableUpdateViewState;
- (void)didMoveToWindow;
- (id)initWithBarButtonItem:(id)arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)layoutSubviews;
- (void)pulse;
- (void)setEnabled:(bool)arg1;
- (void)setProgress:(double)arg1;
- (void)stateController:(id)arg1 transitionDidStop:(id)arg2 completed:(bool)arg3;
- (void)tintColorDidChange;
- (void)updateContents;

@end
