/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface RLMArrayHolder : NSObject {
    /* Warning: unhandled struct encoding: '{unique_ptr<id [], std::__1::default_delete<id []> >="__ptr_"{__compressed_pair<__strong id *, std::__1::default_delete<id []> >="__value_"^@}}' */ struct unique_ptr<id [], std::__1::default_delete<id []> > { 
        struct __compressed_pair<__strong id *, std::__1::default_delete<id []> > { 
            id *__value_; 
        } __ptr_; 
    }  items;
}

- (id).cxx_construct;
- (void).cxx_destruct;

@end
