/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionTitleComponent : CKCompositeComponent {
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<> { 
        unsigned long long _variant; 
        id _target; 
    }  _action;
    bool  _enabled;
    CKComponent * _leadingComponent;
}

+ (id)newWithIcon:(id)arg1 attributedTitle:(id)arg2 enabled:(bool)arg3 action:(struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; })arg4;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)componentTapped:(id)arg1;

@end
