/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFDatePickerButtonComponent : CKCompositeComponent {
    bool  _becomeFirstResponder;
    WFCustomButtonComponent * _buttonComponent;
}

@property (nonatomic, readonly) bool becomeFirstResponder;
@property (nonatomic, readonly) WFCustomButtonComponent *buttonComponent;

+ (id)newWithAttributes:(const struct WFDatePickerAttributes { bool x1; id x2; /* Warning: Unrecognized filer type: 'W' using 'void*' */ void*x3; void*x4; long doublex5; void*x6; void*x7; void*x8; void*x9; int x10; BOOL x11; void*x12; void*x13; const void*x14; int x15; void*x16; long x17; void*x18; void*x19; void*x20; void*x21; BOOL x22; void*x23; void*x24; void*x25; in void*x26; void*x27; id x28; }*)arg1 updateBlock:(id /* block */)arg2 variableBlock:(id /* block */)arg3 size:(const struct CKComponentSize { struct CKRelativeDimension { int x_1_1_1; double x_1_1_2; } x1; struct CKRelativeDimension { int x_2_1_1; double x_2_1_2; } x2; struct CKRelativeDimension { int x_3_1_1; double x_3_1_2; } x3; struct CKRelativeDimension { int x_4_1_1; double x_4_1_2; } x4; struct CKRelativeDimension { int x_5_1_1; double x_5_1_2; } x5; struct CKRelativeDimension { int x_6_1_1; double x_6_1_2; } x6; }*)arg4;

- (void).cxx_destruct;
- (bool)becomeFirstResponder;
- (id)buttonComponent;

@end
