/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFExpansionToggleComponent : CKCompositeComponent {
    CKComponent * _disclosureComponent;
    bool  _expanded;
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<bool>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<bool> { 
        unsigned long long _variant; 
        id _target; 
    }  _toggleAction;
}

+ (id)newWithLabel:(id)arg1 hintLabel:(id)arg2 labelsToAlignTo:(id)arg3 disclosureImage:(id)arg4 toggleAction:(struct CKTypedComponentAction<bool> { unsigned long long x1; id x2; SEL x3; })arg5 expanded:(bool)arg6 style:(const struct WFParameterLayoutComponentStyle { id x1; id x2; }*)arg7;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)toggleChanged;

@end
