/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFMaskedShadowComponent : CKCompositeComponent

+ (id)newWithOptions:(/* Warning: unhandled struct encoding: '{WFMaskedShadowComponentOptions=d@@{CGSize=dd}dd@d@}' */ struct WFMaskedShadowComponentOptions { double x1; id x2; struct CGSize { double x_3_1_1; double x_3_1_2; } x3; double x4; double x5; id x6; id x7; })arg1 component:(id)arg2;

@end
