/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleParameterSelectionRowComponent : CKCompositeComponent {
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<NSString *>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<NSString *> { 
        unsigned long long _variant; 
        id _target; 
    }  _action;
    NSString * _identifier;
}

+ (id)newWithIdentifier:(id)arg1 title:(id)arg2 disabledSubtitle:(id)arg3 enabled:(bool)arg4 action:(struct CKTypedComponentAction<NSString *> { unsigned long long x1; id x2; SEL x3; })arg5 appearance:(id)arg6;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)handleParameterLayoutPressed;

@end
