/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleShowMoreComponent : CKCompositeComponent

+ (id)newWithShowingMore:(bool)arg1 highlightedBackgroundColor:(id)arg2 toggleAction:(struct CKTypedComponentAction<bool> { unsigned long long x1; id x2; SEL x3; })arg3;

@end
