/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleOutputModel : NSObject {
    WFAction * _action;
    bool  _extensionInput;
    UIImage * _icon;
    NSString * _name;
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<WFModuleOutputModel *>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<WFModuleOutputModel *> { 
        unsigned long long _variant; 
        id _target; 
    }  _tapAction;
}

@property (nonatomic, readonly) WFAction *action;
@property (getter=isExtensionInput, nonatomic, readonly) bool extensionInput;
@property (nonatomic, readonly) UIImage *icon;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly) struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; } tapAction;

+ (id)modelForAction:(id)arg1 withTapAction:(struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; })arg2;
+ (id)modelForExtensionInputWithTapAction:(struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; })arg1;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)action;
- (unsigned long long)hash;
- (id)icon;
- (id)initWithAction:(id)arg1 tapAction:(struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; })arg2;
- (id)initWithExtensionInputAndTapAction:(struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; })arg1;
- (bool)isEqual:(id)arg1;
- (bool)isExtensionInput;
- (id)name;
- (struct CKTypedComponentAction<WFModuleOutputModel *> { unsigned long long x1; id x2; SEL x3; })tapAction;

@end
