/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleImportWarningComponent : CKCompositeComponent {
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<unsigned long>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<unsigned long> { 
        unsigned long long _variant; 
        id _target; 
    }  _buttonAction;
}

+ (id)newWithMessage:(id)arg1 buttonTitle:(id)arg2 buttonAction:(struct CKTypedComponentAction<unsigned long> { unsigned long long x1; id x2; SEL x3; })arg3 buttonGradient:(id)arg4 loading:(bool)arg5;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)buttonTapped:(id)arg1;

@end
