/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFNumberPickerButtonComponent : CKCompositeComponent {
    bool  _becomeFirstResponder;
    WFCustomButtonComponent * _buttonComponent;
    id /* block */  _updateBlock;
    id /* block */  _variableBlock;
}

@property (nonatomic, readonly) bool becomeFirstResponder;
@property (nonatomic, readonly) WFCustomButtonComponent *buttonComponent;
@property (nonatomic, readonly) id /* block */ updateBlock;
@property (nonatomic, readonly) id /* block */ variableBlock;

+ (id)newWithAttributes:(const /* Warning: unhandled struct encoding: '{WFNumberPickerAttributes=B@@@Q{_NSRange=QQ}B@@@}' */ struct WFNumberPickerAttributes { bool x1; id x2; id x3; struct _NSRange { unsigned long long x_4_1_1; unsigned long long x_4_1_2; } x4; bool x5; id x6; id x7; }*)arg1 identifier:(id)arg2 updateBlock:(id /* block */)arg3 variableBlock:(id /* block */)arg4;

- (void).cxx_destruct;
- (bool)becomeFirstResponder;
- (id)buttonComponent;
- (id /* block */)updateBlock;
- (id /* block */)variableBlock;

@end
