/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFTextInputComponent : CKStatefulViewComponent {
    struct WFTextInputAttributes { 
        bool editable; 
        bool multiline; 
        bool secureTextEntry; 
        NSString *placeholder; 
        long long keyboardType; 
        long long textAlignment; 
        NSString *textContentType; 
        long long autocorrectionType; 
        long long autocapitalizationType; 
        bool smartQuotesDisabled; 
        bool smartDashesDisabled; 
        bool becomeFirstResponder; 
        WFVariableString *variableString; 
        NSValue *selectedRange; 
        <WFVariableProvider> *variableProvider; 
        <WFVariableUIDelegate> *variableUIDelegate; 
        NSSet *allowedVariableTypes; 
        bool variablesDisabled; 
        UIFont *font; 
        bool throttleUpdates; 
        struct UIEdgeInsets { 
            double top; 
            double left; 
            double bottom; 
            double right; 
        } textContainerInset; 
        UIColor *textColor; 
        UIColor *backgroundColor; 
        unsigned long long syntaxHighlightingType; 
    }  _attributes;
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<> { 
        unsigned long long _variant; 
        id _target; 
    }  _beginAction;
    /* Warning: unhandled struct encoding: '{CKTypedComponentAction<>="_variant"Q"_target"@"_scopeHandle"@"CKComponentScopeHandle""_selector":}' */ struct CKTypedComponentAction<> { 
        unsigned long long _variant; 
        id _target; 
    }  _doneAction;
    id /* block */  _updateBlock;
}

@property (nonatomic, readonly) struct WFTextInputAttributes { bool x1; bool x2; bool x3; id x4; long long x5; id x6; long long x7; bool x8; bool x9; bool x10; id x11; id x12; id x13; id x14; struct UIEdgeInsets { double x_15_1_1; double x_15_1_2; double x_15_1_3; double x_15_1_4; } x15; id x16; unsigned long long x17; } attributes;
@property (nonatomic, readonly) struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; } beginAction;
@property (nonatomic, readonly) struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; } doneAction;
@property (nonatomic, readonly) id /* block */ updateBlock;

+ (id)newWithAttributes:(const struct WFTextInputAttributes { bool x1; bool x2; bool x3; id x4; long long x5; id x6; long long x7; bool x8; bool x9; bool x10; id x11; id x12; id x13; id x14; struct UIEdgeInsets { double x_15_1_1; double x_15_1_2; double x_15_1_3; double x_15_1_4; } x15; id x16; unsigned long long x17; }*)arg1 updateBlock:(id /* block */)arg2 beginAction:(struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; })arg3 doneAction:(struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; })arg4 size:(const struct CKComponentSize { struct CKRelativeDimension { int x_1_1_1; double x_1_1_2; } x1; struct CKRelativeDimension { int x_2_1_1; double x_2_1_2; } x2; struct CKRelativeDimension { int x_3_1_1; double x_3_1_2; } x3; struct CKRelativeDimension { int x_4_1_1; double x_4_1_2; } x4; struct CKRelativeDimension { int x_5_1_1; double x_5_1_2; } x5; struct CKRelativeDimension { int x_6_1_1; double x_6_1_2; } x6; }*)arg5;

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct WFTextInputAttributes { bool x1; bool x2; bool x3; id x4; long long x5; id x6; long long x7; bool x8; bool x9; bool x10; id x11; id x12; id x13; id x14; struct UIEdgeInsets { double x_15_1_1; double x_15_1_2; double x_15_1_3; double x_15_1_4; } x15; id x16; unsigned long long x17; })attributes;
- (struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; })beginAction;
- (struct CKTypedComponentAction<> { unsigned long long x1; id x2; SEL x3; })doneAction;
- (id /* block */)updateBlock;

@end
