/* Generated by RuntimeBrowser.
 */

@protocol CKComponentStateListener <NSObject>

@required

- (void)componentScopeHandleWithIdentifier:(void *)arg1 rootIdentifier:(void *)arg2 didReceiveStateUpdate:(void *)arg3 mode:(void *)arg4; // needs 4 arg types, found 8: int, int, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, id, void*, id, unsigned long long

@end
