/* Generated by RuntimeBrowser.
 */

@protocol CLSettingsManagerProtocol <CLIntersiloServiceProtocol>

@required

- (void)flush;
- (void)refresh;
- (NSDictionary *)syncgetSetValue:(void *)arg1 forKey:(void *)arg2 withoutNotifying:(void *)arg3; // needs 3 arg types, found 4: id, NSString *, /* Warning: Unrecognized filer type: 'R' using 'void*' */ void*, <CLSettingsManagerClientProtocol> *
- (NSDictionary *)syncgetSettingsAndRegisterForUpdates:(void *)arg1; // needs 1 arg types, found 2: /* Warning: Unrecognized filer type: 'R' using 'void*' */ void*, <CLSettingsManagerClientProtocol> *
- (void)unregisterForUpdates:(void *)arg1; // needs 1 arg types, found 2: /* Warning: Unrecognized filer type: 'R' using 'void*' */ void*, <CLSettingsManagerClientProtocol> *

@end
