/* Generated by RuntimeBrowser.
 */

@protocol DNDSModeAssertionStoreRecordDictionaryEncoding <NSObject>

@required

+ (id)recordForDictionary:(NSDictionary *)arg1 keys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; /* Warning: Unrecognized filer type: '2' using 'void*' */ void*x_8_2_3; void*x_8_2_4; } x_1_1_8; } x1; }*)arg2;

- (NSDictionary *)dictionaryWithKeys:(void *)arg1 options:(void *)arg2; // needs 2 arg types, found 1: const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; /* Warning: Unrecognized filer type: '1' using 'void*' */ void*x_8_2_3; void*x_8_2_4; unsigned long long x_8_2_5; void*x_8_2_6; void*x_8_2_7; } x_1_1_8; } x1; }*

@end
