/* Generated by RuntimeBrowser.
 */

@protocol FLEXMultiColumnTableViewDataSource <NSObject>

@required

- (NSString *)columnNameInColumn:(long long)arg1;
- (NSString *)contentAtColumn:(long long)arg1 row:(long long)arg2;
- (NSArray *)contentAtRow:(long long)arg1;
- (double)heightForTopHeaderInTableView:(FLEXMultiColumnTableView *)arg1;
- (double)multiColumnTableView:(FLEXMultiColumnTableView *)arg1 heightForContentCellInRow:(long long)arg2;
- (double)multiColumnTableView:(FLEXMultiColumnTableView *)arg1 widthForContentCellInColumn:(long long)arg2;
- (long long)numberOfColumnsInTableView:(FLEXMultiColumnTableView *)arg1;
- (long long)numberOfRowsInTableView:(FLEXMultiColumnTableView *)arg1;
- (NSString *)rowNameInRow:(long long)arg1;
- (double)widthForLeftHeaderInTableView:(FLEXMultiColumnTableView *)arg1;

@end
