/* Generated by RuntimeBrowser.
 */

@protocol FLEXMultiColumnTableViewDelegate <NSObject>

@required

- (void)multiColumnTableView:(FLEXMultiColumnTableView *)arg1 didTapHeaderWithText:(NSString *)arg2 sortType:(unsigned long long)arg3;
- (void)multiColumnTableView:(FLEXMultiColumnTableView *)arg1 didTapLabelWithText:(NSString *)arg2;

@end
