/* Generated by RuntimeBrowser.
 */

@protocol FLEXHierarchyTableViewControllerDelegate <NSObject>

@required

- (void)hierarchyViewController:(FLEXHierarchyTableViewController *)arg1 didFinishWithSelectedView:(UIView *)arg2;

@end
