/* Generated by RuntimeBrowser.
 */

@protocol FLEXDatabaseManager <NSObject>

@required

- (id)initWithPath:(NSString *)arg1;
- (bool)open;
- (NSArray *)queryAllColumnsWithTableName:(NSString *)arg1;
- (NSArray *)queryAllDataWithTableName:(NSString *)arg1;
- (NSArray *)queryAllTables;

@end
