/* Generated by RuntimeBrowser.
 */

@protocol GPBDictionaryInternalsProtocol

@required

- (unsigned long long)computeSerializedSizeAsField:(GPBFieldDescriptor *)arg1;
- (void)enumerateForTextFormat:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, id, void*
- (void)setGPBGenericValue:(union { bool x1; int x2; long long x3; unsigned int x4; unsigned long long x5; float x6; double x7; id x8; id x9; }*)arg1 forGPBGenericValueKey:(union { bool x1; int x2; long long x3; unsigned int x4; unsigned long long x5; float x6; double x7; id x8; id x9; }*)arg2;
- (void)writeToCodedOutputStream:(GPBCodedOutputStream *)arg1 asField:(GPBFieldDescriptor *)arg2;

@end
