/* Generated by RuntimeBrowser.
 */

@protocol LPAsynchronousResource <NSObject>

@required

- (void)loadAsynchronouslyWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 5: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, id
- (bool)needsAsynchronousLoad;

@end
