/* Generated by RuntimeBrowser.
 */

@protocol MOVStreamPreProcessor <NSObject>

@required

- (unsigned int)encodedPixelFormatFromStreamData:(struct StreamRecordingData { struct opaqueCMFormatDescription {} *x1; bool x2; id x3; id x4; id x5; id /* block */ x6; id x7; id x8; struct __CVPixelBufferPool {} x9; id x10; }*)arg1;
- (const struct opaqueCMFormatDescription { }*)formatDescriptionForPixelBuffer:(struct __CVBuffer { }*)arg1 streamData:(struct StreamRecordingData { struct opaqueCMFormatDescription {} *x1; bool x2; id x3; id x4; id x5; id /* block */ x6; id x7; id x8; struct __CVPixelBufferPool {} x9; id x10; }*)arg2;
- (unsigned int)inputPixelFormatFromStreamData:(struct StreamRecordingData { struct opaqueCMFormatDescription {} *x1; bool x2; id x3; id x4; id x5; id /* block */ x6; id x7; id x8; struct __CVPixelBufferPool {} x9; id x10; }*)arg1;
- (struct __CVBuffer { }*)processedPixelBufferCopyOf:(struct __CVBuffer { }*)arg1 streamData:(struct StreamRecordingData { struct opaqueCMFormatDescription {} *x1; bool x2; id x3; id x4; id x5; id /* block */ x6; id x7; id x8; struct __CVPixelBufferPool {} x9; id x10; }*)arg2 error:(id*)arg3;
- (const struct opaqueCMFormatDescription { }*)trackFormatDescriptionFromStreamData:(struct StreamRecordingData { struct opaqueCMFormatDescription {} *x1; bool x2; id x3; id x4; id x5; id /* block */ x6; id x7; id x8; struct __CVPixelBufferPool {} x9; id x10; }*)arg1;

@end
