/* Generated by RuntimeBrowser.
 */

@protocol SGSuggestionCategory <NSObject>

@required

- (NSString *)suggestionCategoryId;
- (UIImage *)suggestionCategoryImage;
- (NSString *)suggestionCategoryLocalizedCountOfItems:(NSArray *)arg1;
- (NSString *)suggestionCategorySubtitleForItems:(NSArray *)arg1;
- (NSString *)suggestionCategoryTitle;
- (NSString *)suggestionCategoryTitleForItems:(NSArray *)arg1;

@optional

- (id /* block */)suggestionComparator:(void *)arg1; // needs 1 arg types, found 5: id /* block */, id, void*, id, SEL

@end
