/* Generated by RuntimeBrowser.
 */

@protocol XPC_IO_Gateway

@required

- (NSObject<OS_xpc_object> *)send_io_message:(struct XPC_Message_Payload { unsigned int x1; unsigned int x2; id x3; /* Warning: Unrecognized filer type: '1' using 'void*' */ void*x4; void*x5; })arg1;

@end
