/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SidecarCore.framework/SidecarCore
 */

@interface SidecarResponse : SidecarRequest {
    bool  _accepted;
}

- (void)_willConnect;
- (void)accept;
- (void)sendItems:(id)arg1;

@end
