/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreHaptics.framework/CoreHaptics
 */

@interface CHMetricsPlayerData : NSObject {
    struct Data { 
        NSString *name; 
    }  _data;
}

@property /* Warning: unhandled struct encoding: '{Data=@}' */ struct Data { id x1; } data;

- (id).cxx_construct;
- (void).cxx_destruct;
- (/* Warning: unhandled struct encoding: '{Data=@}' */ struct Data { id x1; })data;
- (void)setData:(/* Warning: unhandled struct encoding: '{Data=@}' */ struct Data { id x1; })arg1;

@end
