/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSModeAssertionStoreRecord : NSObject <DNDSModeAssertionStoreRecordDictionaryEncoding> {
    NSArray * _assertions;
    NSArray * _invalidationRequests;
    NSArray * _invalidations;
}

@property (nonatomic, retain) NSArray *assertions;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *invalidationRequests;
@property (nonatomic, retain) NSArray *invalidations;
@property (readonly) Class superclass;

+ (id)recordForAssertionStore:(id)arg1;
+ (id)recordForDictionary:(id)arg1 keys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg2;

- (void).cxx_destruct;
- (id)assertions;
- (id)dictionaryWithKeys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg1 options:(unsigned long long)arg2;
- (id)invalidationRequests;
- (id)invalidations;
- (id)object;
- (void)setAssertions:(id)arg1;
- (void)setInvalidationRequests:(id)arg1;
- (void)setInvalidations:(id)arg1;

@end
