/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSModeAssertionInvalidationPredicateRecord : NSObject <DNDSModeAssertionStoreRecordDictionaryEncoding> {
    NSArray * _UUIDs;
    NSArray * _clientIdentifiers;
    NSNumber * _date;
    NSString * _predicateType;
}

@property (nonatomic, retain) NSArray *UUIDs;
@property (nonatomic, retain) NSArray *clientIdentifiers;
@property (nonatomic, retain) NSNumber *date;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *predicateType;
@property (readonly) Class superclass;

+ (id)recordForDictionary:(id)arg1 keys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg2;
+ (id)recordForInvalidationPredicate:(id)arg1;

- (void).cxx_destruct;
- (id)UUIDs;
- (id)clientIdentifiers;
- (id)date;
- (id)dictionaryWithKeys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg1 options:(unsigned long long)arg2;
- (id)object;
- (id)predicateType;
- (void)setClientIdentifiers:(id)arg1;
- (void)setDate:(id)arg1;
- (void)setPredicateType:(id)arg1;
- (void)setUUIDs:(id)arg1;

@end
