/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSModeAssertionInvalidationRequestRecord : NSObject <DNDSModeAssertionStoreRecordDictionaryEncoding> {
    NSString * _UUID;
    DNDSModeAssertionInvalidationDetailsRecord * _details;
    DNDSModeAssertionInvalidationPredicateRecord * _predicate;
    NSString * _reason;
    NSString * _reasonOverride;
    NSNumber * _requestDate;
    DNDSModeAssertionSourceRecord * _source;
}

@property (nonatomic, retain) NSString *UUID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) DNDSModeAssertionInvalidationDetailsRecord *details;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) DNDSModeAssertionInvalidationPredicateRecord *predicate;
@property (nonatomic, retain) NSString *reason;
@property (nonatomic, retain) NSString *reasonOverride;
@property (nonatomic, retain) NSNumber *requestDate;
@property (nonatomic, retain) DNDSModeAssertionSourceRecord *source;
@property (readonly) Class superclass;

+ (id)recordForDictionary:(id)arg1 keys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg2;
+ (id)recordForInvalidationRequest:(id)arg1;

- (void).cxx_destruct;
- (id)UUID;
- (id)details;
- (id)dictionaryWithKeys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg1 options:(unsigned long long)arg2;
- (id)object;
- (id)predicate;
- (id)reason;
- (id)reasonOverride;
- (id)requestDate;
- (void)setDetails:(id)arg1;
- (void)setPredicate:(id)arg1;
- (void)setReason:(id)arg1;
- (void)setReasonOverride:(id)arg1;
- (void)setRequestDate:(id)arg1;
- (void)setSource:(id)arg1;
- (void)setUUID:(id)arg1;
- (id)source;

@end
