/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSModeAssertionLifetimeRecord : NSObject <DNDSModeAssertionStoreRecordDictionaryEncoding> {
    NSString * _behavior;
    NSNumber * _endDate;
    NSString * _eventUniqueID;
    NSString * _lifetimeType;
    NSNumber * _occurrenceDate;
    NSNumber * _onlyDuringEvent;
    NSString * _scheduleIdentifier;
    NSNumber * _startDate;
}

@property (nonatomic, retain) NSString *behavior;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSNumber *endDate;
@property (nonatomic, retain) NSString *eventUniqueID;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *lifetimeType;
@property (nonatomic, retain) NSNumber *occurrenceDate;
@property (nonatomic, retain) NSNumber *onlyDuringEvent;
@property (nonatomic, retain) NSString *scheduleIdentifier;
@property (nonatomic, retain) NSNumber *startDate;
@property (readonly) Class superclass;

+ (id)recordForAssertionLifetime:(id)arg1;
+ (id)recordForDictionary:(id)arg1 keys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg2;

- (void).cxx_destruct;
- (id)behavior;
- (id)dictionaryWithKeys:(const struct { struct { id x_1_1_1; id x_1_1_2; struct { id x_3_2_1; id x_3_2_2; } x_1_1_3; struct { id x_4_2_1; id x_4_2_2; } x_1_1_4; struct { id x_5_2_1; id x_5_2_2; id x_5_2_3; id x_5_2_4; } x_1_1_5; struct { id x_6_2_1; } x_1_1_6; struct { id x_7_2_1; id x_7_2_2; id x_7_2_3; } x_1_1_7; /* Warning: unhandled struct encoding: '{?=@}{?=@@@@@@@}{?=@@@@}}' */ struct { id x_8_2_1; struct { id x_2_3_1; id x_2_3_2; id x_2_3_3; id x_2_3_4; struct { id x_5_4_1; id x_5_4_2; } x_2_3_5; } x_8_2_2; } x_1_1_8; } x1; }*)arg1 options:(unsigned long long)arg2;
- (id)endDate;
- (id)eventUniqueID;
- (id)lifetimeType;
- (id)object;
- (id)occurrenceDate;
- (id)onlyDuringEvent;
- (id)scheduleIdentifier;
- (void)setBehavior:(id)arg1;
- (void)setEndDate:(id)arg1;
- (void)setEventUniqueID:(id)arg1;
- (void)setLifetimeType:(id)arg1;
- (void)setOccurrenceDate:(id)arg1;
- (void)setOnlyDuringEvent:(id)arg1;
- (void)setScheduleIdentifier:(id)arg1;
- (void)setStartDate:(id)arg1;
- (id)startDate;

@end
