/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AirPlayReceiver.framework/AirPlayReceiver
 */

@interface AirPlayReceiverPlatform : NSObject {
    AirPlayControllerServer * _controllerServer;
    unsigned char  _isAmbientAudioPlaying;
    unsigned char  _isMediaAudioPlaying;
    unsigned char  _isMuted;
    unsigned char  _isVideoPlaying;
    int  _lockDownActivationStateToken;
    int  _managedDefaultsChangedNotificationToken;
    int  _playbackAllowNotifyToken;
    int  _playbackPreventNotifyToken;
    unsigned char  _playbackPrevented;
    int  _prefChangedNotifyToken;
    struct AirPlayReceiverServerPrivate { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned long long x_1_1_2; } x1; void *x2; id x3; int x4; struct OpaqueAPAdvertiser {} *x5; unsigned char x6; unsigned char x7; struct HTTPServerPrivate {} *x8; id x9; struct HTTPServerPrivate {} x10; unsigned char x11[16]; float x12; unsigned char x13; int x14; unsigned char x15; unsigned char x16; id x17; unsigned long long x18; struct OpaqueAPReceiverSystemInfo {} *x19; unsigned char x20; unsigned char x21; struct __CFDictionary {} *x22; struct __CFDictionary {} *x23; struct __CFDictionary {} *x24; unsigned int x25; int x26; unsigned int x27; struct APReceiverSessionManagerOpaque {} *x28; struct OpaqueFigValeria {} *x29; int (*x30)(); struct __CFString {} *x31; struct __CFString {} *x32; unsigned char x33; unsigned char x34; unsigned char x35; unsigned char x36; unsigned char x37; unsigned char x38; unsigned char x39; } * _server;
    unsigned long long  _stalledSessionCount;
    int  _systemBufferSamples;
    int  _systemSampleRate;
    int  _uiErrorNotifyToken;
    unsigned char  _voiceForSiri;
    unsigned char  _voiceForTelephony;
    int  _volumeControlType;
    float  _volumeSliderValue;
    float  _volumeSliderValueBeforeMute;
    NSString * _wifiDECaptureUUID;
    DEExtension * _wifiDiagnosticExtension;
}

@property (nonatomic) unsigned char isAmbientAudioPlaying;
@property (nonatomic) unsigned char isMediaAudioPlaying;
@property (nonatomic) unsigned char isVideoPlaying;

- (void)_avSystemControllerVolumeChanged:(id)arg1;
- (void)_avSystemControllerVolumeConfigChanged:(id)arg1;
- (void)_handleAVAudioSessionInterruption:(id)arg1;
- (void)_handleAVAudioSessionServicesReset:(id)arg1;
- (void)_handleVolumeControlTypeChange;
- (void)_setupVolumeNotificationHandlers;
- (void)_updateMediaSessionActivationStateBasedOnMediaAudioPlayingState:(unsigned char)arg1 andVideoPlayingState:(unsigned char)arg2;
- (unsigned char)isAmbientAudioPlaying;
- (unsigned char)isMediaAudioPlaying;
- (unsigned char)isVideoPlaying;
- (void)setIsAmbientAudioPlaying:(unsigned char)arg1;
- (void)setIsMediaAudioPlaying:(unsigned char)arg1;
- (void)setIsVideoPlaying:(unsigned char)arg1;

@end
