/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface FxBitmapImage : NSObject {
    struct FxBitmapImagePriv { id x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; int x3; struct CGColorSpace {} *x4; struct CGContext {} *x5; struct CGImage {} *x6; struct CGDataProvider {} *x7; } * _priv;
}

+ (id)bitmapWithData:(id)arg1 bytesPerRow:(unsigned long long)arg2 size:(struct CGSize { double x1; double x2; })arg3 format:(int)arg4 colorSpace:(struct CGColorSpace { }*)arg5;
+ (id)bitmapWithSize:(struct CGSize { double x1; double x2; })arg1 format:(int)arg2 colorSpace:(struct CGColorSpace { }*)arg3;

- (void*)bytes;
- (unsigned long long)bytesPerRow;
- (struct CGContext { }*)cgContext;
- (struct CGImage { }*)cgImage;
- (struct CGColorSpace { }*)colorSpace;
- (id)data;
- (void)dealloc;
- (id)initWithData:(id)arg1 bytesPerRow:(unsigned long long)arg2 size:(struct CGSize { double x1; double x2; })arg3 format:(int)arg4 colorSpace:(struct CGColorSpace { }*)arg5;
- (int)pixelFormat;
- (struct CGSize { double x1; double x2; })size;

@end
