/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface FxParameterPoint3d : FxPinParameter {
    /* Warning: unhandled struct encoding: '{FxParameterPoint3dPriv=@}' */ struct FxParameterPoint3dPriv { id x1; } * _point3dPriv;
}

- (void)dealloc;
- (id)init;

@end
