/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface FxParameterGroup : FxPinParameter {
    /* Warning: unhandled struct encoding: '{FxParameterGroupPriv=@}' */ struct FxParameterGroupPriv { id x1; } * _groupPriv;
}

- (void)dealloc;
- (id)init;
- (void)setSubPins:(id)arg1;
- (id)subPins;

@end
