/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface ___4_______________1________3_______________$_______________4_____ : NSObject <LAListener> {
    bool  ____4_______________1________3_______________$_______________1_____;
    int  ____4_______________2________3_______________$_______________0_____;
}

@property (readonly) bool ___4_______________1________3_______________$_______________1_____;
@property (readonly) int ___4_______________2________3_______________$_______________0_____;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (void)load;

- (id)___4_______________1________3_______________$_______________0_____:(bool)arg1 ___4_______________2________3_______________$_______________0_____:(long long)arg2;
- (bool)___4_______________1________3_______________$_______________1_____;
- (int)___4_______________2________3_______________$_______________0_____;
- (void)activator:(id)arg1 abortEvent:(id)arg2;
- (void)activator:(id)arg1 receiveEvent:(id)arg2;
- (id)activator:(id)arg1 requiresIconDataForListenerName:(id)arg2 scale:(double*)arg3;
- (id)activator:(id)arg1 requiresLocalizedDescriptionForListenerName:(id)arg2;
- (id)activator:(id)arg1 requiresLocalizedGroupForListenerName:(id)arg2;
- (id)activator:(id)arg1 requiresLocalizedTitleForListenerName:(id)arg2;
- (id)activator:(id)arg1 requiresSmallIconDataForListenerName:(id)arg2 scale:(double*)arg3;

@end
