/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface SIAlertBackgroundWindowÊèíÊèíÂ§¥xxtÈó∑Â£∞Èò≤Â§ßÂÜ≤Á™Å : UIWindow {
    long long  _style;
}

@property (nonatomic) long long style;

- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 andStyle:(long long)arg2;
- (void)setStyle:(long long)arg1;
- (long long)style;

@end
