/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface SIAlertItemÊèíÊèíÂ§¥xxtÈó∑Â£∞Èò≤Â§ßÂÜ≤Á™Å : NSObject {
    id /* block */  _action;
    NSString * _title;
    long long  _type;
}

@property (nonatomic, copy) id /* block */ action;
@property (nonatomic, copy) NSString *title;
@property (nonatomic) long long type;

- (void).cxx_destruct;
- (id /* block */)action;
- (void)setAction:(id /* block */)arg1;
- (void)setTitle:(id)arg1;
- (void)setType:(long long)arg1;
- (id)title;
- (long long)type;

@end
