/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface SIToastWindowÊèíÊèíÂ§¥xxtÈó∑Â£∞Èò≤Â§ßÂÜ≤Á™Å : UIWindow

- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;

@end
