/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface UIAlertViewBlockDelegateÊèíÊèíÂ§¥xxtÈó∑Â£∞Èò≤Â§ßÂÜ≤Á™Å : NSObject

+ (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
+ (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
+ (void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
+ (void)alertViewCancel:(id)arg1;
+ (bool)alertViewShouldEnableFirstOtherButton:(id)arg1;
+ (void)didPresentAlertView:(id)arg1;
+ (void)willPresentAlertView:(id)arg1;

@end
