/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface XXTouchNotificationClient : NSObject

+ (id)dataForKey:(id)arg1;
+ (id)popBackDataForKey:(id)arg1;
+ (id)popBackDictionaryForKey:(id)arg1;
+ (id)popDataForKey:(id)arg1;
+ (id)popDictionaryForKey:(id)arg1;
+ (id)popFrontDataForKey:(id)arg1;
+ (id)popFrontDictionaryForKey:(id)arg1;
+ (int)pushBackData:(id)arg1 forKey:(id)arg2;
+ (int)pushBackDictionary:(id)arg1 forKey:(id)arg2;
+ (int)pushData:(id)arg1 forKey:(id)arg2;
+ (int)pushDictionary:(id)arg1 forKey:(id)arg2;
+ (int)pushFrontData:(id)arg1 forKey:(id)arg2;
+ (int)pushFrontDictionary:(id)arg1 forKey:(id)arg2;
+ (id)putData:(id)arg1 forKey:(id)arg2;
+ (id)send:(id)arg1 toName:(id)arg2;
+ (id)sendRequest:(id)arg1 path:(id)arg2 headers:(id)arg3 query:(id)arg4 body:(id)arg5;

@end
