/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface XXTTouchEvent : NSObject {
    struct CGPoint { 
        double x; 
        double y; 
    }  point;
    float  pressure;
    int  type;
    float  z;
}

@end
