/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface XXTUIWebWindow : UIWindow {
    bool  _canDrag;
    struct CGPoint { 
        double x; 
        double y; 
    }  _gestureBeganPosition;
}

- (void)ااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااا:(id)arg1;

@end
