/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface ÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿß : UIViewController {
    AVCaptureDevice * _avc_device;
    AVCaptureSession * ÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿß;
}

- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)ااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااا;
- (void)اااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااا;
- (void)ااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااا;
- (void)اااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااااا;

@end
