/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/1feaks.dylib
 */

@interface ÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿßÿß : NSObject {
    int (* _callBack;
    NSDictionary * _reply;
}

- (void)dealloc;
- (id)init;
- (id)اااااااااااااااااااااااااااااااااااااا:(id)arg1 ااااااااااااااااااااااااااااااااااااا:(id)arg2;
- (void)ااااااااااااااااااااااااااااااااااااااا:(id)arg1 اااااااااااااااااااااااااااااااااااااا:(int (*)arg2;

@end
