/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSUFileProviderUtilities : NSObject

+ (void)bookmarkableStringFromDocumentURL:(id)arg1 completionQueue:(id)arg2 completion:(id /* block */)arg3;
+ (void)didUpdateAlternateContentsDocumentForSandboxedURL:(id)arg1 completionQueue:(id)arg2 completion:(id /* block */)arg3;
+ (void)fetchAlternateContentsURLForSandboxedURL:(id)arg1 completionQueue:(id)arg2 completion:(id /* block */)arg3;
+ (void)initialize;
+ (void)setAlternateContentsURL:(id)arg1 onSandboxedURL:(id)arg2 completionQueue:(id)arg3 completion:(id /* block */)arg4;

- (id)init;

@end
