/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSUURLTracker : NSObject <TSUURLWrapper> {
    TSUURLTrackerFilePresenter * _filePresenter;
    <TSULogContext> * _logContext;
}

@property (readonly) NSURL *URL;
@property (readonly) NSURL *URLIfAvailable;
@property (readonly) NSData *bookmarkData;
@property (readonly) NSData *bookmarkDataIfAvailable;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) bool deleted;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isValid;
@property (nonatomic, readonly) <TSULogContext> *logContext;
@property (readonly) TSUSandboxedURL *sandboxedURL;
@property (readonly) TSUSandboxedURL *sandboxedURLIfAvailable;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)URL;
- (id)URLIfAvailable;
- (id)bookmarkData;
- (id)bookmarkDataAndReturnError:(id*)arg1;
- (id)bookmarkDataIfAvailable;
- (void)dealloc;
- (bool)deleted;
- (id)description;
- (id)init;
- (id)initWithBookmarkData:(id)arg1;
- (id)initWithBookmarkData:(id)arg1 delegate:(id)arg2;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 bookmarkData:(id)arg2 delegate:(id)arg3;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;
- (bool)isValid;
- (id)logContext;
- (id)p_filePresenterQueue;
- (void)pause;
- (id)recalculateBookmarkDataAndReturnError:(id*)arg1;
- (id)recalculateSandboxedURLAndReturnError:(id*)arg1;
- (void)resume;
- (id)sandboxedURL;
- (id)sandboxedURLAndReturnError:(id*)arg1;
- (id)sandboxedURLIfAvailable;
- (void)stop;

@end
