/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PUTemporaryImageTable : PLTemporaryImageTable {
    int  _indexCounter;
}

- (int)nextCacheIndex;

@end
