/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGMetalRenderTextureStore : NSObject {
    long long  _capacity;
    long long  _count;
    bool  _sorted;
    struct { id x1; /* Warning: Unrecognized filer type: '_' using 'void*' */ void*x2; inout unsigned short x3; void*x4; void*x5; in void*x6; void*x7; void*x8; unsigned long long x9; unsigned long long x10; } * _textures;
}

- (void)_sortIfNeeded;
- (void)addTexture:(struct { id x1; /* Warning: Unrecognized filer type: '_' using 'void*' */ void*x2; inout unsigned short x3; void*x4; void*x5; in void*x6; void*x7; void*x8; unsigned long long x9; unsigned long long x10; })arg1;
- (void)dealloc;
- (void)drawWithOrder:(unsigned long long)arg1 enumerationBlock:(id /* block */)arg2;
- (id)init;
- (void)removeAllTextures;

@end
