/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXKeyboardHelpViewController : UIViewController {
    UITextView * _textView;
}

@property (nonatomic, retain) UITextView *textView;

- (void).cxx_destruct;
- (void)donePressed:(id)arg1;
- (void)setTextView:(id)arg1;
- (id)textView;
- (void)viewDidLoad;

@end
