/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkDetailRow : NSObject {
    NSString * _detailText;
    id /* block */  _selectionFuture;
    NSString * _title;
}

@property (nonatomic, copy) NSString *detailText;
@property (nonatomic, copy) id /* block */ selectionFuture;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (id)detailText;
- (id /* block */)selectionFuture;
- (void)setDetailText:(id)arg1;
- (void)setSelectionFuture:(id /* block */)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
