/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputViewFactory : NSObject

+ (id)argumentInputViewForTypeEncoding:(const char *)arg1;
+ (id)argumentInputViewForTypeEncoding:(const char *)arg1 currentValue:(id)arg2;
+ (Class)argumentInputViewSubclassForTypeEncoding:(const char *)arg1 currentValue:(id)arg2;
+ (bool)canEditFieldWithTypeEncoding:(const char *)arg1 currentValue:(id)arg2;

@end
