/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXDefaultEditorViewController : FLEXMutableFieldEditorViewController {
    NSString * _key;
}

@property (nonatomic, readonly) NSUserDefaults *defaults;
@property (nonatomic, retain) NSString *key;

+ (bool)canEditDefaultWithValue:(id)arg1;

- (void).cxx_destruct;
- (void)actionButtonPressed:(id)arg1;
- (id)defaults;
- (void)getterButtonPressed:(id)arg1;
- (id)initWithDefaults:(id)arg1 key:(id)arg2;
- (id)key;
- (void)setKey:(id)arg1;
- (void)viewDidLoad;

@end
