/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXTableView : UITableView

@property (nonatomic, readonly) NSString *defaultReuseIdentifier;
@property (nonatomic, readonly) NSString *multilineReuseIdentifier;
@property (nonatomic, readonly) NSString *subtitleReuseIdentifier;

- (double)_heightForHeaderInSection:(long long)arg1;
- (id)defaultReuseIdentifier;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 style:(long long)arg2;
- (id)multilineReuseIdentifier;
- (void)registerCells:(id)arg1;
- (id)subtitleReuseIdentifier;

@end
