/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXColorPreviewBox : UIView {
    UIView * _colorOverlayView;
}

@property (nonatomic, retain) UIColor *color;
@property (nonatomic, retain) UIView *colorOverlayView;

+ (id)backgroundPatternImage;

- (void).cxx_destruct;
- (id)color;
- (id)colorOverlayView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setColor:(id)arg1;
- (void)setColorOverlayView:(id)arg1;

@end
