/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXKeychainTableViewController : FLEXTableViewController <FLEXGlobalsEntry> {
    NSArray * _keyChainItems;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *keyChainItems;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)addPressed;
- (id)keyChainItems;
- (void)refreshKeychainItems;
- (void)setKeyChainItems:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)trashPressed;
- (void)viewDidLoad;

@end
