/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputNumberView : FLEXArgumentInputTextView

+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;

- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (void)setInputValue:(id)arg1;

@end
