/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXDictionaryExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) NSDictionary *dictionary;

- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)dictionary;
- (bool)shouldShowDescription;

@end
