/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkTransactionDetailTableViewController : UITableViewController {
    NSArray * _sections;
    FLEXNetworkTransaction * _transaction;
}

@property (nonatomic, copy) NSArray *sections;
@property (nonatomic, retain) FLEXNetworkTransaction *transaction;

+ (id)attributedTextForRow:(id)arg1;
+ (id)detailViewControllerForMIMEType:(id)arg1 data:(id)arg2;
+ (id)generalSectionForTransaction:(id)arg1;
+ (id)networkDetailRowsFromDictionary:(id)arg1;
+ (id)postBodyDataForTransaction:(id)arg1;
+ (id)postBodySectionForTransaction:(id)arg1;
+ (id)queryParametersSectionForTransaction:(id)arg1;
+ (id)requestHeadersSectionForTransaction:(id)arg1;
+ (id)responseHeadersSectionForTransaction:(id)arg1;

- (void).cxx_destruct;
- (void)copyButtonPressed:(id)arg1;
- (void)handleTransactionUpdatedNotification:(id)arg1;
- (id)initWithStyle:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)rebuildTableSections;
- (id)rowModelAtIndexPath:(id)arg1;
- (id)sections;
- (void)setSections:(id)arg1;
- (void)setTransaction:(id)arg1;
- (bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)transaction;
- (void)viewDidLoad;

@end
