/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXInternalRequestState : NSObject {
    NSMutableData * _dataAccumulator;
    NSURLRequest * _request;
}

@property (nonatomic, retain) NSMutableData *dataAccumulator;
@property (nonatomic, copy) NSURLRequest *request;

- (void).cxx_destruct;
- (id)dataAccumulator;
- (id)request;
- (void)setDataAccumulator:(id)arg1;
- (void)setRequest:(id)arg1;

@end
