/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputDateView : FLEXArgumentInputView {
    UIDatePicker * _datePicker;
}

@property (nonatomic, retain) UIDatePicker *datePicker;

+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;

- (void).cxx_destruct;
- (id)datePicker;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (void)layoutSubviews;
- (void)setDatePicker:(id)arg1;
- (void)setInputValue:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
