/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXClassesTableViewController : FLEXTableViewController <FLEXGlobalsEntry> {
    NSString * _binaryImageName;
    NSArray * _classNames;
    NSArray * _filteredClassNames;
}

@property (nonatomic, copy) NSString *binaryImageName;
@property (nonatomic, retain) NSArray *classNames;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSArray *filteredClassNames;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (id)binaryImageName;
- (id)classNames;
- (id)filteredClassNames;
- (void)loadClassNames;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setBinaryImageName:(id)arg1;
- (void)setClassNames:(id)arg1;
- (void)setFilteredClassNames:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateSearchResults:(id)arg1;
- (void)updateTitle;
- (void)viewDidLoad;

@end
