/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXClassExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) Class theClass;

- (bool)canCallInstanceMethods;
- (bool)canHaveInstanceState;
- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)possibleExplorerSections;
- (bool)shouldShowDescription;
- (Class)theClass;

@end
