/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArrayExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) NSArray *array;

- (id)array;
- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)detailObjectForRowCookie:(id)arg1;
- (bool)shouldShowDescription;

@end
