/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputNotSupportedView : FLEXArgumentInputTextView

- (id)initWithArgumentTypeEncoding:(const char *)arg1;

@end
