/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXSubtitleTableViewCell : UITableViewCell

- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
