/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXColor : NSObject

+ (id)borderColor;
+ (id)deemphasizedTextColor;
+ (id)hairlineColor;
+ (id)iconColor;
+ (id)primaryBackgroundColor;
+ (id)primaryBackgroundColorWithAlpha:(double)arg1;
+ (id)primaryTextColor;
+ (id)scrollViewBackgroundColor;
+ (id)secondaryBackgroundColor;
+ (id)secondaryBackgroundColorWithAlpha:(double)arg1;
+ (id)tertiaryBackgroundColor;
+ (id)tertiaryBackgroundColorWithAlpha:(double)arg1;
+ (id)tintColor;
+ (id)toolbarItemHighlightedColor;
+ (id)toolbarItemSelectedColor;

@end
