/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXFileBrowserSearchOperation : NSOperation {
    <FLEXFileBrowserSearchOperationDelegate> * _delegate;
    NSString * _path;
    NSString * _searchString;
}

@property (nonatomic) <FLEXFileBrowserSearchOperationDelegate> *delegate;
@property (nonatomic, retain) NSString *path;
@property (nonatomic, retain) NSString *searchString;

- (void).cxx_destruct;
- (id)delegate;
- (id)initWithPath:(id)arg1 searchString:(id)arg2;
- (void)main;
- (id)path;
- (id)searchString;
- (void)setDelegate:(id)arg1;
- (void)setPath:(id)arg1;
- (void)setSearchString:(id)arg1;
- (unsigned long long)totalSizeAtPath:(id)arg1;

@end
