/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputStructView : FLEXArgumentInputView {
    NSArray * _argumentInputViews;
}

@property (nonatomic, retain) NSArray *argumentInputViews;

+ (id)customFieldTitlesForTypeEncoding:(const char *)arg1;
+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;
+ (double)verticalPaddingBetweenFields;

- (void).cxx_destruct;
- (id)argumentInputViews;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (bool)inputViewIsFirstResponder;
- (void)layoutSubviews;
- (void)setArgumentInputViews:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setInputValue:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
