/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXColorExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) UIColor *colorObject;

- (id)colorObject;
- (bool)customSectionCanDrillIntoRowWithCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionTitle;
- (id)customViewForRowCookie:(id)arg1;
- (id)displayedObjectDescription;

@end
