/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkHistoryTableViewController : FLEXTableViewController <FLEXGlobalsEntry> {
    long long  _bytesReceived;
    long long  _filteredBytesReceived;
    NSArray * _filteredNetworkTransactions;
    bool  _isPresentingSearch;
    NSArray * _networkTransactions;
    bool  _rowInsertInProgress;
}

@property (nonatomic) long long bytesReceived;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long filteredBytesReceived;
@property (nonatomic, copy) NSArray *filteredNetworkTransactions;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isPresentingSearch;
@property (nonatomic, copy) NSArray *networkTransactions;
@property (nonatomic) bool rowInsertInProgress;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (long long)bytesReceived;
- (void)dealloc;
- (void)didPresentSearchController:(id)arg1;
- (long long)filteredBytesReceived;
- (id)filteredNetworkTransactions;
- (void)handleNetworkObserverEnabledStateChangedNotification:(id)arg1;
- (void)handleNewTransactionRecordedNotification:(id)arg1;
- (void)handleTransactionUpdatedNotification:(id)arg1;
- (void)handleTransactionsClearedNotification:(id)arg1;
- (id)headerText;
- (id)init;
- (bool)isPresentingSearch;
- (id)networkTransactions;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (bool)rowInsertInProgress;
- (void)setBytesReceived:(long long)arg1;
- (void)setFilteredBytesReceived:(long long)arg1;
- (void)setFilteredNetworkTransactions:(id)arg1;
- (void)setIsPresentingSearch:(bool)arg1;
- (void)setNetworkTransactions:(id)arg1;
- (void)setRowInsertInProgress:(bool)arg1;
- (void)settingsButtonTapped:(id)arg1;
- (void)settingsViewControllerDoneTapped:(id)arg1;
- (bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (id)transactionAtIndexPath:(id)arg1 inTableView:(id)arg2;
- (void)tryUpdateTransactions;
- (void)updateBytesReceived;
- (void)updateFilteredBytesReceived;
- (void)updateFirstSectionHeader;
- (void)updateSearchResults:(id)arg1;
- (void)updateTransactions;
- (void)viewDidLoad;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentSearchController:(id)arg1;

@end
