/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXAddressExplorerCoordinator : NSObject <FLEXGlobalsEntry>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id /* block */)globalsEntryRowAction:(unsigned long long)arg1;
+ (id)globalsEntryTitle:(unsigned long long)arg1;

@end
