/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXFieldEditorView : UIView {
    NSArray * _argumentInputViews;
    NSString * _fieldDescription;
    UIView * _fieldDescriptionDivider;
    UILabel * _fieldDescriptionLabel;
    NSString * _targetDescription;
    UIView * _targetDescriptionDivider;
    UILabel * _targetDescriptionLabel;
}

@property (nonatomic, retain) NSArray *argumentInputViews;
@property (nonatomic, copy) NSString *fieldDescription;
@property (nonatomic, retain) UIView *fieldDescriptionDivider;
@property (nonatomic, retain) UILabel *fieldDescriptionLabel;
@property (nonatomic, copy) NSString *targetDescription;
@property (nonatomic, retain) UIView *targetDescriptionDivider;
@property (nonatomic, retain) UILabel *targetDescriptionLabel;

+ (id)dividerColor;
+ (double)dividerLineHeight;
+ (id)dividerView;
+ (double)horizontalPadding;
+ (id)labelFont;
+ (double)verticalPadding;

- (void).cxx_destruct;
- (id)argumentInputViews;
- (id)fieldDescription;
- (id)fieldDescriptionDivider;
- (id)fieldDescriptionLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)setArgumentInputViews:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setFieldDescription:(id)arg1;
- (void)setFieldDescriptionDivider:(id)arg1;
- (void)setFieldDescriptionLabel:(id)arg1;
- (void)setTargetDescription:(id)arg1;
- (void)setTargetDescriptionDivider:(id)arg1;
- (void)setTargetDescriptionLabel:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)targetDescription;
- (id)targetDescriptionDivider;
- (id)targetDescriptionLabel;

@end
