/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXTableViewCell : UITableViewCell

- (bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)forwardInvocation:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;

@end
