/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXTableLeftCell : UITableViewCell {
    UILabel * _titlelabel;
}

@property (nonatomic, retain) UILabel *titlelabel;

+ (id)cellWithTableView:(id)arg1;

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setTitlelabel:(id)arg1;
- (id)titlelabel;

@end
