/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXMethodBox : NSObject {
    struct objc_method { } * _method;
}

@property (nonatomic) struct objc_method { }*method;

- (struct objc_method { }*)method;
- (void)setMethod:(struct objc_method { }*)arg1;

@end
