/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXCarouselCell : UICollectionViewCell {
    bool  _constraintsInstalled;
    UIView * _selectionIndicatorStripe;
    UILabel * _titleLabel;
}

@property (nonatomic) bool constraintsInstalled;
@property (nonatomic, readonly) UIView *selectionIndicatorStripe;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, readonly) UILabel *titleLabel;

- (void).cxx_destruct;
- (bool)constraintsInstalled;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)installConstraints;
- (void)prepareForReuse;
- (id)selectionIndicatorStripe;
- (void)setConstraintsInstalled:(bool)arg1;
- (void)setSelected:(bool)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)titleLabel;
- (void)updateAppearance;

@end
