/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXFieldEditorViewController : UIViewController <UIScrollViewDelegate> {
    FLEXFieldEditorView * _fieldEditorView;
    UIScrollView * _scrollView;
    UIBarButtonItem * _setterButton;
    id  _target;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) FLEXFieldEditorView *fieldEditorView;
@property (nonatomic, readonly) FLEXArgumentInputView *firstInputView;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIScrollView *scrollView;
@property (nonatomic, retain) UIBarButtonItem *setterButton;
@property (readonly) Class superclass;
@property (nonatomic, retain) id target;

- (void).cxx_destruct;
- (void)actionButtonPressed:(id)arg1;
- (void)dealloc;
- (void)exploreObjectOrPopViewController:(id)arg1;
- (id)fieldEditorView;
- (id)firstInputView;
- (id)initWithTarget:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (id)scrollView;
- (void)setFieldEditorView:(id)arg1;
- (void)setScrollView:(id)arg1;
- (void)setSetterButton:(id)arg1;
- (void)setTarget:(id)arg1;
- (id)setterButton;
- (id)target;
- (id)titleForActionButton;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
