/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXObjectRef : NSObject {
    id  _object;
    NSString * _reference;
}

@property (nonatomic, readonly) id object;
@property (nonatomic, readonly) NSString *reference;

+ (id)referencing:(id)arg1;
+ (id)referencing:(id)arg1 ivar:(id)arg2;
+ (id)referencingAll:(id)arg1;

- (void).cxx_destruct;
- (id)initWithObject:(id)arg1 ivarName:(id)arg2;
- (id)object;
- (id)reference;

@end
