/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXSystemLogTableViewController : FLEXTableViewController <FLEXGlobalsEntry> {
    NSArray * _filteredLogMessages;
    <FLEXLogController> * _logController;
    NSMutableArray * _logMessages;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSArray *filteredLogMessages;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) <FLEXLogController> *logController;
@property (nonatomic, readonly) NSMutableArray *logMessages;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (id)filteredLogMessages;
- (void)handleUpdateWithNewMessages:(id)arg1;
- (id)init;
- (id)logController;
- (id)logMessageAtIndexPath:(id)arg1;
- (id)logMessages;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollToLastRow;
- (void)setFilteredLogMessages:(id)arg1;
- (void)showLogSettings;
- (bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (void)updateSearchResults:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
