/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputObjectView : FLEXArgumentInputTextView {
    unsigned long long  _inputType;
    UISegmentedControl * _objectTypeSegmentControl;
}

@property (nonatomic) unsigned long long inputType;
@property (nonatomic, retain) UISegmentedControl *objectTypeSegmentControl;

+ (unsigned long long)preferredDefaultTypeForObjCType:(const char *)arg1 withCurrentValue:(id)arg2;
+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;

- (void).cxx_destruct;
- (void)didChangeType;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (unsigned long long)inputType;
- (id)inputValue;
- (void)layoutSubviews;
- (id)objectTypeSegmentControl;
- (void)populateTextAreaFromValue:(id)arg1;
- (void)setInputType:(unsigned long long)arg1;
- (void)setInputValue:(id)arg1;
- (void)setObjectTypeSegmentControl:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (double)topInputFieldVerticalLayoutGuide;

@end
