/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkRecorder : NSObject {
    NSArray * _hostBlacklist;
    NSMutableDictionary * _networkTransactionsForRequestIdentifiers;
    NSMutableArray * _orderedTransactions;
    NSObject<OS_dispatch_queue> * _queue;
    NSCache * _responseCache;
    bool  _shouldCacheMediaResponses;
}

@property (nonatomic, copy) NSArray *hostBlacklist;
@property (nonatomic, retain) NSMutableDictionary *networkTransactionsForRequestIdentifiers;
@property (nonatomic, retain) NSMutableArray *orderedTransactions;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic, retain) NSCache *responseCache;
@property (nonatomic) unsigned long long responseCacheByteLimit;
@property (nonatomic) bool shouldCacheMediaResponses;

+ (id)defaultRecorder;

- (void).cxx_destruct;
- (id)cachedResponseBodyForTransaction:(id)arg1;
- (void)clearRecordedActivity;
- (id)hostBlacklist;
- (id)init;
- (id)networkTransactions;
- (id)networkTransactionsForRequestIdentifiers;
- (id)orderedTransactions;
- (void)postNewTransactionNotificationWithTransaction:(id)arg1;
- (void)postUpdateNotificationForTransaction:(id)arg1;
- (id)queue;
- (void)recordDataReceivedWithRequestID:(id)arg1 dataLength:(long long)arg2;
- (void)recordLoadingFailedWithRequestID:(id)arg1 error:(id)arg2;
- (void)recordLoadingFinishedWithRequestID:(id)arg1 responseBody:(id)arg2;
- (void)recordMechanism:(id)arg1 forRequestID:(id)arg2;
- (void)recordRequestWillBeSentWithRequestID:(id)arg1 request:(id)arg2 redirectResponse:(id)arg3;
- (void)recordResponseReceivedWithRequestID:(id)arg1 response:(id)arg2;
- (id)responseCache;
- (unsigned long long)responseCacheByteLimit;
- (void)setHostBlacklist:(id)arg1;
- (void)setNetworkTransactionsForRequestIdentifiers:(id)arg1;
- (void)setOrderedTransactions:(id)arg1;
- (void)setQueue:(id)arg1;
- (void)setResponseCache:(id)arg1;
- (void)setResponseCacheByteLimit:(unsigned long long)arg1;
- (void)setShouldCacheMediaResponses:(bool)arg1;
- (bool)shouldCacheMediaResponses;

@end
