/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXMultilineTableViewCell : FLEXTableViewCell

+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })labelInsets;
+ (double)preferredHeightWithAttributedText:(id)arg1 inTableViewWidth:(double)arg2 style:(long long)arg3 showsAccessory:(bool)arg4;

- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end
