/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXPropertyEditorViewController : FLEXMutableFieldEditorViewController <FLEXArgumentInputViewDelegate> {
    struct objc_property { } * _property;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) struct objc_property { }*property;
@property (readonly) Class superclass;

+ (bool)canEditProperty:(struct objc_property { }*)arg1 onObject:(id)arg2 currentValue:(id)arg3;

- (void)actionButtonPressed:(id)arg1;
- (void)argumentInputViewValueDidChange:(id)arg1;
- (void)getterButtonPressed:(id)arg1;
- (id)initWithTarget:(id)arg1 property:(struct objc_property { }*)arg2;
- (struct objc_property { }*)property;
- (void)setProperty:(struct objc_property { }*)arg1;
- (void)viewDidLoad;

@end
