/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXWindow : UIWindow {
    <FLEXWindowEventDelegate> * _eventDelegate;
}

@property (nonatomic) <FLEXWindowEventDelegate> *eventDelegate;

+ (void)initialize;

- (void).cxx_destruct;
- (bool)_canAffectStatusBarAppearance;
- (bool)_canBecomeKeyWindow;
- (bool)canBecomeKeyWindow;
- (id)eventDelegate;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)pointInside:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (void)setEventDelegate:(id)arg1;
- (bool)shouldAffectStatusBarAppearance;

@end
