/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXIvarBox : NSObject {
    struct objc_ivar { } * _ivar;
}

@property (nonatomic) struct objc_ivar { }*ivar;

- (struct objc_ivar { }*)ivar;
- (void)setIvar:(struct objc_ivar { }*)arg1;

@end
