/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputColorView : FLEXArgumentInputView <FLEXColorComponentInputViewDelegate> {
    FLEXColorComponentInputView * _alphaInput;
    FLEXColorComponentInputView * _blueInput;
    FLEXColorPreviewBox * _colorPreviewBox;
    FLEXColorComponentInputView * _greenInput;
    UILabel * _hexLabel;
    FLEXColorComponentInputView * _redInput;
}

@property (nonatomic, retain) FLEXColorComponentInputView *alphaInput;
@property (nonatomic, retain) FLEXColorComponentInputView *blueInput;
@property (nonatomic, retain) FLEXColorPreviewBox *colorPreviewBox;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) FLEXColorComponentInputView *greenInput;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UILabel *hexLabel;
@property (nonatomic, retain) FLEXColorComponentInputView *redInput;
@property (readonly) Class superclass;

+ (double)colorPreviewBoxHeight;
+ (double)inputViewVerticalPadding;
+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;

- (void).cxx_destruct;
- (id)alphaInput;
- (id)blueInput;
- (void)colorComponentInputViewValueDidChange:(id)arg1;
- (id)colorPreviewBox;
- (id)greenInput;
- (id)hexLabel;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (void)layoutSubviews;
- (id)redInput;
- (void)setAlphaInput:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setBlueInput:(id)arg1;
- (void)setColorPreviewBox:(id)arg1;
- (void)setGreenInput:(id)arg1;
- (void)setHexLabel:(id)arg1;
- (void)setInputValue:(id)arg1;
- (void)setRedInput:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (void)updateColorPreview;
- (void)updateWithColor:(id)arg1;

@end
