/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputView : UIView {
    <FLEXArgumentInputViewDelegate> * _delegate;
    id  _inputValue;
    unsigned long long  _targetSize;
    NSString * _title;
    UILabel * _titleLabel;
    NSString * _typeEncoding;
}

@property (nonatomic) <FLEXArgumentInputViewDelegate> *delegate;
@property (nonatomic, retain) id inputValue;
@property (nonatomic, readonly) bool inputViewIsFirstResponder;
@property (nonatomic) unsigned long long targetSize;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) UILabel *titleLabel;
@property (nonatomic, readonly) double topInputFieldVerticalLayoutGuide;
@property (nonatomic, retain) NSString *typeEncoding;

+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;
+ (double)titleBottomPadding;
+ (id)titleFont;

- (void).cxx_destruct;
- (id)delegate;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (bool)inputViewIsFirstResponder;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setInputValue:(id)arg1;
- (void)setTargetSize:(unsigned long long)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setTypeEncoding:(id)arg1;
- (bool)showsTitle;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (unsigned long long)targetSize;
- (id)title;
- (id)titleLabel;
- (double)topInputFieldVerticalLayoutGuide;
- (id)typeEncoding;

@end
