/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXSystemLogMessage : NSObject {
    struct __asl_object_s { } * _aslMessage;
    NSDate * _date;
    long long  _messageID;
    NSString * _messageText;
    NSString * _sender;
}

@property (nonatomic, readonly) struct __asl_object_s { }*aslMessage;
@property (nonatomic, readonly) NSDate *date;
@property (nonatomic, readonly) long long messageID;
@property (nonatomic, readonly) NSString *messageText;
@property (nonatomic, readonly) NSString *sender;

+ (id)logMessageFromASLMessage:(struct __asl_object_s { }*)arg1;
+ (id)logMessageFromDate:(id)arg1 text:(id)arg2;

- (void).cxx_destruct;
- (struct __asl_object_s { }*)aslMessage;
- (id)date;
- (id)description;
- (unsigned long long)hash;
- (id)initWithDate:(id)arg1 sender:(id)arg2 text:(id)arg3 messageID:(long long)arg4;
- (bool)isEqual:(id)arg1;
- (long long)messageID;
- (id)messageText;
- (id)sender;

@end
