/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkDetailSection : NSObject {
    NSArray * _rows;
    NSString * _title;
}

@property (nonatomic, copy) NSArray *rows;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (id)rows;
- (void)setRows:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
