/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXExplorerViewController : UIViewController <FLEXGlobalsTableViewControllerDelegate, FLEXHierarchyTableViewControllerDelegate> {
    unsigned long long  _currentMode;
    <FLEXExplorerViewControllerDelegate> * _delegate;
    UITapGestureRecognizer * _detailsTapGR;
    FLEXExplorerToolbar * _explorerToolbar;
    UIPanGestureRecognizer * _movePanGR;
    NSMutableSet * _observedViews;
    NSDictionary * _outlineViewsForVisibleViews;
    UIWindow * _previousKeyWindow;
    UIView * _selectedView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _selectedViewFrameBeforeDragging;
    UIView * _selectedViewOverlay;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _toolbarFrameBeforeDragging;
    NSArray * _viewsAtTapPoint;
}

@property (nonatomic) unsigned long long currentMode;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <FLEXExplorerViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UITapGestureRecognizer *detailsTapGR;
@property (nonatomic, retain) FLEXExplorerToolbar *explorerToolbar;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIPanGestureRecognizer *movePanGR;
@property (nonatomic, retain) NSMutableSet *observedViews;
@property (nonatomic, retain) NSDictionary *outlineViewsForVisibleViews;
@property (nonatomic, retain) UIWindow *previousKeyWindow;
@property (nonatomic, retain) UIView *selectedView;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } selectedViewFrameBeforeDragging;
@property (nonatomic, retain) UIView *selectedViewOverlay;
@property (readonly) Class superclass;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } toolbarFrameBeforeDragging;
@property (nonatomic, retain) NSArray *viewsAtTapPoint;

+ (id)viewKeyPathsToTrack;

- (void).cxx_destruct;
- (id)allRecursiveSubviewsInView:(id)arg1;
- (id)allViewsInHierarchy;
- (void)beginObservingView:(id)arg1;
- (void)closeButtonTapped:(id)arg1;
- (unsigned long long)currentMode;
- (void)dealloc;
- (id)delegate;
- (id)detailsTapGR;
- (id)explorerToolbar;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameInLocalCoordinatesForView:(id)arg1;
- (void)globalsButtonTapped:(id)arg1;
- (void)globalsViewControllerDidFinish:(id)arg1;
- (void)handleDownArrowKeyPressed;
- (void)handleLeftArrowKeyPressed;
- (void)handleMovePan:(id)arg1;
- (void)handleRightArrowKeyPressed;
- (void)handleSelectionTap:(id)arg1;
- (void)handleToolbarDetailsTapGesture:(id)arg1;
- (void)handleToolbarHintTapGesture:(id)arg1;
- (void)handleToolbarPanGesture:(id)arg1;
- (void)handleUpArrowKeyPressed;
- (void)hierarchyButtonTapped:(id)arg1;
- (id)hierarchyDepthsForViews:(id)arg1;
- (void)hierarchyViewController:(id)arg1 didFinishWithSelectedView:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)makeKeyAndPresentViewController:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)moveButtonTapped:(id)arg1;
- (id)movePanGR;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)observedViews;
- (id)outlineViewForView:(id)arg1;
- (id)outlineViewsForVisibleViews;
- (id)previousKeyWindow;
- (id)recursiveSubviewsAtPoint:(struct CGPoint { double x1; double x2; })arg1 inView:(id)arg2 skipHiddenViews:(bool)arg3;
- (void)removeAndClearOutlineViews;
- (void)resignKeyAndDismissViewControllerAnimated:(bool)arg1 completion:(id /* block */)arg2;
- (void)selectButtonTapped:(id)arg1;
- (id)selectedView;
- (void)selectedViewExplorerFinished:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })selectedViewFrameBeforeDragging;
- (id)selectedViewOverlay;
- (void)setCurrentMode:(unsigned long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDetailsTapGR:(id)arg1;
- (void)setExplorerToolbar:(id)arg1;
- (void)setMovePanGR:(id)arg1;
- (void)setObservedViews:(id)arg1;
- (void)setOutlineViewsForVisibleViews:(id)arg1;
- (void)setPreviousKeyWindow:(id)arg1;
- (void)setSelectedView:(id)arg1;
- (void)setSelectedViewFrameBeforeDragging:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setSelectedViewOverlay:(id)arg1;
- (void)setToolbarFrameBeforeDragging:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setViewsAtTapPoint:(id)arg1;
- (void)setupToolbarActions;
- (void)setupToolbarGestures;
- (bool)shouldAutorotate;
- (bool)shouldReceiveTouchAtWindowPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)statusWindow;
- (void)stopObservingView:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)toggleMenuTool;
- (void)toggleMoveTool;
- (void)toggleSelectTool;
- (void)toggleToolWithViewControllerProvider:(id /* block */)arg1 completion:(id /* block */)arg2;
- (void)toggleViewsTool;
- (void)toggleViewsToolWithCompletion:(id /* block */)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })toolbarFrameBeforeDragging;
- (void)updateButtonStates;
- (void)updateOutlineViewsForSelectionPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)updateOverlayAndDescriptionForObjectIfNeeded:(id)arg1;
- (void)updateSelectedViewPositionWithDragGesture:(id)arg1;
- (void)updateToolbarPositionWithDragGesture:(id)arg1;
- (void)updateToolbarPositionWithUnconstrainedFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)viewControllerForRotationAndOrientation;
- (void)viewDidLoad;
- (id)viewForSelectionAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })viewSafeArea;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (id)viewsAtPoint:(struct CGPoint { double x1; double x2; })arg1 skipHiddenViews:(bool)arg2;
- (id)viewsAtTapPoint;
- (bool)wantsWindowToBecomeKey;

@end
