/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXInstancesTableViewController : UITableViewController {
    NSArray * _instances;
    NSArray * _predicates;
    NSArray * _sectionTitles;
    NSArray * _sections;
}

@property (nonatomic, retain) NSArray *instances;
@property (nonatomic, readonly) long long maxSections;
@property (nonatomic, retain) NSArray *predicates;
@property (nonatomic, retain) NSArray *sectionTitles;
@property (nonatomic, retain) NSArray *sections;

+ (id)defaultPredicateForSection:(long long)arg1;
+ (id)defaultPredicates;
+ (id)defaultSectionTitles;
+ (id)instancesTableViewControllerForClassName:(id)arg1;
+ (id)instancesTableViewControllerForInstancesReferencingObject:(id)arg1;

- (void).cxx_destruct;
- (void)buildSections;
- (id)initWithReferences:(id)arg1;
- (id)initWithReferences:(id)arg1 predicates:(id)arg2 sectionTitles:(id)arg3;
- (id)instances;
- (long long)maxSections;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)predicates;
- (id)sectionTitles;
- (id)sections;
- (void)setInstances:(id)arg1;
- (void)setPredicates:(id)arg1;
- (void)setSectionTitles:(id)arg1;
- (void)setSections:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;

@end
