/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXUtility : NSObject

+ (id)addressOfObject:(id)arg1;
+ (id)alert:(id)arg1 message:(id)arg2;
+ (id)allWindows;
+ (id)applicationImageName;
+ (id)applicationName;
+ (id)circularImageWithColor:(id)arg1 radius:(double)arg2;
+ (id)consistentRandomColorForObject:(id)arg1;
+ (id)defaultFontOfSize:(double)arg1;
+ (id)defaultTableViewCellLabelFont;
+ (id)descriptionForView:(id)arg1 includingFrame:(bool)arg2;
+ (id)detailDescriptionForView:(id)arg1;
+ (id)dictionaryFromQuery:(id)arg1;
+ (id)hierarchyIndentPatternColor;
+ (id)inflatedDataFromCompressedData:(id)arg1;
+ (unsigned long long)infoPlistSupportedInterfaceOrientationsMask;
+ (bool)instanceRespondsButDoesNotImplementSelector:(SEL)arg1 class:(Class)arg2;
+ (bool)isErrorStatusCodeFromURLResponse:(id)arg1;
+ (bool)isValidJSONData:(id)arg1;
+ (id)map:(id)arg1 block:(id /* block */)arg2;
+ (id)prettyJSONStringFromData:(id)arg1;
+ (void)replaceImplementationOfKnownSelector:(SEL)arg1 onClass:(Class)arg2 withBlock:(id)arg3 swizzledSelector:(SEL)arg4;
+ (void)replaceImplementationOfSelector:(SEL)arg1 withSelector:(SEL)arg2 forClass:(Class)arg3 withMethodDescription:(struct objc_method_description { SEL x1; char *x2; })arg4 implementationBlock:(id)arg5 undefinedBlock:(id)arg6;
+ (id)safeDebugDescriptionForObject:(id)arg1;
+ (id)safeDescriptionForObject:(id)arg1;
+ (id)statusCodeStringFromURLResponse:(id)arg1;
+ (id)stringByEscapingHTMLEntitiesInString:(id)arg1;
+ (id)stringForCGRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
+ (id)stringFromRequestDuration:(double)arg1;
+ (SEL)swizzledSelectorForSelector:(SEL)arg1;
+ (id)thumbnailedImageWithMaxPixelDimension:(long long)arg1 fromImageData:(id)arg2;
+ (id)viewControllerForAncestralView:(id)arg1;
+ (id)viewControllerForView:(id)arg1;

@end
