/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXPropertyBox : NSObject {
    struct objc_property { } * _property;
}

@property (nonatomic) struct objc_property { }*property;

- (struct objc_property { }*)property;
- (void)setProperty:(struct objc_property { }*)arg1;

@end
