/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXLayerExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) CALayer *layerToExplore;

+ (id)imagePreviewViewControllerForLayer:(id)arg1;

- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)layerToExplore;

@end
