/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXResources : NSObject

+ (id)audioIcon;
+ (id)binaryIcon;
+ (id)checkerPattern;
+ (id)closeIcon;
+ (id)dragHandle;
+ (id)globeIcon;
+ (id)hierarchyIndentPattern;
+ (id)htmlIcon;
+ (id)imageWithBytesNoCopy:(void*)arg1 length:(unsigned long long)arg2 scale:(double)arg3;
+ (id)jsIcon;
+ (id)jsonIcon;
+ (id)listIcon;
+ (id)moveIcon;
+ (id)plistIcon;
+ (id)selectIcon;
+ (id)textIcon;
+ (id)textPlainIcon;
+ (id)videoIcon;
+ (id)xmlIcon;

@end
