/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXNetworkTransaction : NSObject {
    NSData * _cachedRequestBody;
    double  _duration;
    NSError * _error;
    double  _latency;
    long long  _receivedDataLength;
    NSURLRequest * _request;
    NSString * _requestID;
    NSString * _requestMechanism;
    NSURLResponse * _response;
    UIImage * _responseThumbnail;
    NSDate * _startTime;
    long long  _transactionState;
}

@property (nonatomic, retain) NSData *cachedRequestBody;
@property (nonatomic) double duration;
@property (nonatomic, retain) NSError *error;
@property (nonatomic) double latency;
@property (nonatomic) long long receivedDataLength;
@property (nonatomic, retain) NSURLRequest *request;
@property (nonatomic, copy) NSString *requestID;
@property (nonatomic, copy) NSString *requestMechanism;
@property (nonatomic, retain) NSURLResponse *response;
@property (nonatomic, retain) UIImage *responseThumbnail;
@property (nonatomic, retain) NSDate *startTime;
@property (nonatomic) long long transactionState;

+ (id)readableStringFromTransactionState:(long long)arg1;

- (void).cxx_destruct;
- (id)cachedRequestBody;
- (id)description;
- (double)duration;
- (id)error;
- (double)latency;
- (long long)receivedDataLength;
- (id)request;
- (id)requestID;
- (id)requestMechanism;
- (id)response;
- (id)responseThumbnail;
- (void)setCachedRequestBody:(id)arg1;
- (void)setDuration:(double)arg1;
- (void)setError:(id)arg1;
- (void)setLatency:(double)arg1;
- (void)setReceivedDataLength:(long long)arg1;
- (void)setRequest:(id)arg1;
- (void)setRequestID:(id)arg1;
- (void)setRequestMechanism:(id)arg1;
- (void)setResponse:(id)arg1;
- (void)setResponseThumbnail:(id)arg1;
- (void)setStartTime:(id)arg1;
- (void)setTransactionState:(long long)arg1;
- (id)startTime;
- (long long)transactionState;

@end
