/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXBundleExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) NSBundle *bundleToExplore;

- (id)bundleToExplore;
- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)shortcutPropertyNames;

@end
