/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXLiveObjectsTableViewController : FLEXTableViewController <FLEXGlobalsEntry> {
    NSArray * _filteredClassNames;
    NSDictionary * _instanceCountsForClassNames;
    NSDictionary * _instanceSizesForClassNames;
}

@property (nonatomic, readonly) NSArray *allClassNames;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSArray *filteredClassNames;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSDictionary *instanceCountsForClassNames;
@property (nonatomic, retain) NSDictionary *instanceSizesForClassNames;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (id)allClassNames;
- (id)filteredClassNames;
- (id)instanceCountsForClassNames;
- (id)instanceSizesForClassNames;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshControlDidRefresh:(id)arg1;
- (void)reloadTableData;
- (void)setFilteredClassNames:(id)arg1;
- (void)setInstanceCountsForClassNames:(id)arg1;
- (void)setInstanceSizesForClassNames:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateSearchResults:(id)arg1;
- (void)updateTitle;
- (void)viewDidLoad;

@end
