/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXTableContentViewController : UIViewController <FLEXMultiColumnTableViewDataSource, FLEXMultiColumnTableViewDelegate> {
    NSArray * _columnsArray;
    NSArray * _contentsArray;
    FLEXMultiColumnTableView * _multiColumnView;
}

@property (nonatomic, retain) NSArray *columnsArray;
@property (nonatomic, retain) NSArray *contentsArray;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) FLEXMultiColumnTableView *multiColumnView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)columnNameInColumn:(long long)arg1;
- (id)columnsArray;
- (id)contentAtColumn:(long long)arg1 row:(long long)arg2;
- (id)contentAtRow:(long long)arg1;
- (id)contentsArray;
- (double)heightForTopHeaderInTableView:(id)arg1;
- (void)multiColumnTableView:(id)arg1 didTapHeaderWithText:(id)arg2 sortType:(unsigned long long)arg3;
- (void)multiColumnTableView:(id)arg1 didTapLabelWithText:(id)arg2;
- (double)multiColumnTableView:(id)arg1 heightForContentCellInRow:(long long)arg2;
- (double)multiColumnTableView:(id)arg1 widthForContentCellInColumn:(long long)arg2;
- (id)multiColumnView;
- (long long)numberOfColumnsInTableView:(id)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)rowNameInRow:(long long)arg1;
- (void)setColumnsArray:(id)arg1;
- (void)setContentsArray:(id)arg1;
- (void)setMultiColumnView:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (double)widthForLeftHeaderInTableView:(id)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

@end
