/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXCookiesTableViewController : UITableViewController <FLEXGlobalsEntry> {
    NSArray * _cookies;
}

@property (nonatomic, retain) NSArray *cookies;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (id)cookieForRowAtIndexPath:(id)arg1;
- (id)cookies;
- (id)initWithStyle:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setCookies:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

@end
