/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXHeapEnumerator : NSObject

+ (void)enumerateLiveObjectsUsingBlock:(id /* block */)arg1;
+ (void)updateRegisteredClasses;

@end
