/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXSQLiteDatabaseManager : NSObject <FLEXDatabaseManager> {
    NSString * _databasePath;
    struct sqlite3 { } * _db;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)close;
- (id)dataForColumnIndex:(int)arg1 stmt:(struct sqlite3_stmt { }*)arg2;
- (id)executeQuery:(id)arg1;
- (id)initWithPath:(id)arg1;
- (id)objectForColumnIndex:(int)arg1 stmt:(struct sqlite3_stmt { }*)arg2;
- (bool)open;
- (id)queryAllColumnsWithTableName:(id)arg1;
- (id)queryAllDataWithTableName:(id)arg1;
- (id)queryAllTables;
- (id)stringForColumnIndex:(int)arg1 stmt:(struct sqlite3_stmt { }*)arg2;

@end
