/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXViewExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) UIView *viewToExplore;

+ (id)imagePreviewViewControllerForView:(id)arg1;
+ (void)initialize;

- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)shortcutPropertyNames;
- (id)viewToExplore;

@end
