/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXFileBrowserTableViewController : FLEXTableViewController <FLEXFileBrowserSearchOperationDelegate, FLEXGlobalsEntry> {
    NSArray * _childPaths;
    UIDocumentInteractionController * _documentController;
    NSOperationQueue * _operationQueue;
    NSString * _path;
    NSNumber * _recursiveSize;
    NSArray * _searchPaths;
    NSNumber * _searchPathsSize;
}

@property (nonatomic, copy) NSArray *childPaths;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIDocumentInteractionController *documentController;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSOperationQueue *operationQueue;
@property (nonatomic, copy) NSString *path;
@property (nonatomic, retain) NSNumber *recursiveSize;
@property (nonatomic, retain) NSArray *searchPaths;
@property (nonatomic, retain) NSNumber *searchPathsSize;
@property (readonly) Class superclass;

+ (id)globalsEntryTitle:(unsigned long long)arg1;
+ (id)globalsEntryViewController:(unsigned long long)arg1;

- (void).cxx_destruct;
- (id)childPaths;
- (id)documentController;
- (void)fileBrowserCopyPath:(id)arg1;
- (void)fileBrowserDelete:(id)arg1;
- (void)fileBrowserRename:(id)arg1;
- (void)fileBrowserSearchOperationResult:(id)arg1 size:(unsigned long long)arg2;
- (void)fileBrowserShare:(id)arg1;
- (id)filePathAtIndexPath:(id)arg1;
- (id)init;
- (id)initWithPath:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openFileController:(id)arg1;
- (id)operationQueue;
- (id)path;
- (id)recursiveSize;
- (void)reloadCurrentPath;
- (void)reloadDisplayedPaths;
- (id)searchPaths;
- (id)searchPathsSize;
- (void)setChildPaths:(id)arg1;
- (void)setDocumentController:(id)arg1;
- (void)setOperationQueue:(id)arg1;
- (void)setPath:(id)arg1;
- (void)setRecursiveSize:(id)arg1;
- (void)setSearchPaths:(id)arg1;
- (void)setSearchPathsSize:(id)arg1;
- (bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)updateSearchPaths;
- (void)updateSearchResults:(id)arg1;
- (void)viewDidLoad;
- (void)willDismissSearchController:(id)arg1;

@end
