/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXTableColumnHeader : UIView {
    UILabel * _arrowLabel;
    UILabel * _label;
}

@property (nonatomic, retain) UILabel *label;

- (void).cxx_destruct;
- (void)changeSortStatusWithType:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)label;
- (void)setLabel:(id)arg1;

@end
