/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXViewControllerExplorerViewController : FLEXObjectExplorerViewController

@property (nonatomic, readonly) UIViewController *viewController;

- (bool)canPushViewController;
- (bool)customSectionCanDrillIntoRowWithCookie:(id)arg1;
- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitle;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)viewController;

@end
