/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXFileBrowserTableViewCell : UITableViewCell

- (void)fileBrowserCopyPath:(id)arg1;
- (void)fileBrowserDelete:(id)arg1;
- (void)fileBrowserRename:(id)arg1;
- (void)fileBrowserShare:(id)arg1;
- (void)forwardAction:(SEL)arg1 withSender:(id)arg2;

@end
