/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXHierarchyTableViewCell : UITableViewCell {
    UIImageView * _colorCircleImageView;
    UIView * _depthIndicatorView;
    UIView * _viewBackgroundColorView;
    UIColor * _viewColor;
    long long  _viewDepth;
}

@property (nonatomic, retain) UIImageView *colorCircleImageView;
@property (nonatomic, retain) UIView *depthIndicatorView;
@property (nonatomic, retain) UIView *viewBackgroundColorView;
@property (nonatomic, retain) UIColor *viewColor;
@property (nonatomic) long long viewDepth;

- (void).cxx_destruct;
- (id)colorCircleImageView;
- (id)depthIndicatorView;
- (id)initWithReuseIdentifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setColorCircleImageView:(id)arg1;
- (void)setDepthIndicatorView:(id)arg1;
- (void)setHighlighted:(bool)arg1 animated:(bool)arg2;
- (void)setSelected:(bool)arg1 animated:(bool)arg2;
- (void)setViewBackgroundColorView:(id)arg1;
- (void)setViewColor:(id)arg1;
- (void)setViewDepth:(long long)arg1;
- (id)viewBackgroundColorView;
- (id)viewColor;
- (long long)viewDepth;

@end
