/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXMutableFieldEditorViewController : FLEXFieldEditorViewController {
    UIBarButtonItem * _getterButton;
}

@property (nonatomic, retain) UIBarButtonItem *getterButton;

- (void).cxx_destruct;
- (id)getterButton;
- (void)getterButtonPressed:(id)arg1;
- (void)setGetterButton:(id)arg1;
- (id)titleForGetterButton;
- (void)viewDidLoad;

@end
