/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXOSLogController : NSObject <FLEXLogController> {
    bool  _canPrint;
    int  _filterPid;
    bool  _levelInfo;
    NSMutableArray * _messages;
    bool  _persistent;
    struct os_activity_stream_s { } * _stream;
    bool  _subsystemInfo;
    id /* block */  _updateHandler;
}

@property (nonatomic) bool canPrint;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) int filterPid;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool levelInfo;
@property (nonatomic, retain) NSMutableArray *messages;
@property (nonatomic) bool persistent;
@property (nonatomic) struct os_activity_stream_s { }*stream;
@property (nonatomic) bool subsystemInfo;
@property (readonly) Class superclass;
@property (nonatomic, copy) id /* block */ updateHandler;

+ (void)load;
+ (id)sharedLogController;
+ (id)withUpdateHandler:(id /* block */)arg1;

- (void).cxx_destruct;
- (bool)canPrint;
- (void)dealloc;
- (int)filterPid;
- (bool)handleStreamEntry:(struct os_activity_stream_entry_s { unsigned int x1; int x2; unsigned long long x3; char *x4; char *x5; unsigned long long x6; unsigned long long x7; union { struct os_activity_stream_common_s { unsigned long long x_1_2_1; unsigned long long x_1_2_2; unsigned long long x_1_2_3; char *x_1_2_4; char *x_1_2_5; struct timeval { long long x_6_3_1; int x_6_3_2; } x_1_2_6; struct timezone { int x_7_3_1; int x_7_3_2; } x_1_2_7; unsigned int x_1_2_8; } x_8_1_1; struct os_activity_create_s { unsigned long long x_2_2_1; unsigned long long x_2_2_2; unsigned long long x_2_2_3; char *x_2_2_4; char *x_2_2_5; struct timeval { long long x_6_3_1; int x_6_3_2; } x_2_2_6; struct timezone { int x_7_3_1; int x_7_3_2; } x_2_2_7; unsigned int x_2_2_8; char *x_2_2_9; unsigned long long x_2_2_10; unsigned long long x_2_2_11; } x_8_1_2; struct os_activity_transition_s { unsigned long long x_3_2_1; unsigned long long x_3_2_2; unsigned long long x_3_2_3; char *x_3_2_4; char *x_3_2_5; struct timeval { long long x_6_3_1; int x_6_3_2; } x_3_2_6; struct timezone { int x_7_3_1; int x_7_3_2; } x_3_2_7; unsigned int x_3_2_8; unsigned long long x_3_2_9; } x_8_1_3; struct os_log_message_s { unsigned long long x_4_2_1; unsigned long long x_4_2_2; unsigned long long x_4_2_3; char *x_4_2_4; char *x_4_2_5; struct timeval { long long x_6_3_1; int x_6_3_2; } x_4_2_6; struct timezone { int x_7_3_1; int x_7_3_2; } x_4_2_7; unsigned int x_4_2_8; char *x_4_2_9; char *x_4_2_10; unsigned long long x_4_2_11; char *x_4_2_12; unsigned long long x_4_2_13; char *x_4_2_14; char *x_4_2_15; unsigned int x_4_2_16; unsigned char x_4_2_17; bool x_4_2_18; } x_8_1_4; } x8; }*)arg1 error:(int)arg2;
- (id)init;
- (bool)levelInfo;
- (bool)lookupSPICalls;
- (id)messages;
- (bool)persistent;
- (void)setCanPrint:(bool)arg1;
- (void)setFilterPid:(int)arg1;
- (void)setLevelInfo:(bool)arg1;
- (void)setMessages:(id)arg1;
- (void)setPersistent:(bool)arg1;
- (void)setStream:(struct os_activity_stream_s { }*)arg1;
- (void)setSubsystemInfo:(bool)arg1;
- (void)setUpdateHandler:(id /* block */)arg1;
- (bool)startMonitoring;
- (struct os_activity_stream_s { }*)stream;
- (id /* block */)streamEventHandlerBlock;
- (bool)subsystemInfo;
- (id /* block */)updateHandler;

@end
