/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXMethodCallingViewController : FLEXFieldEditorViewController {
    struct objc_method { } * _method;
    BOOL * _returnType;
}

@property (nonatomic) struct objc_method { }*method;
@property (nonatomic) BOOL*returnType;

- (void)actionButtonPressed:(id)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 method:(struct objc_method { }*)arg2;
- (bool)isClassMethod;
- (struct objc_method { }*)method;
- (BOOL*)returnType;
- (void)setMethod:(struct objc_method { }*)arg1;
- (void)setReturnType:(BOOL*)arg1;
- (id)titleForActionButton;
- (void)viewDidLoad;

@end
