/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputSwitchView : FLEXArgumentInputView {
    UISwitch * _inputSwitch;
}

@property (nonatomic, retain) UISwitch *inputSwitch;

+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;

- (void).cxx_destruct;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputSwitch;
- (id)inputValue;
- (void)layoutSubviews;
- (void)setInputSwitch:(id)arg1;
- (void)setInputValue:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (void)switchValueDidChange:(id)arg1;

@end
