/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXSystemLogTableViewCell : UITableViewCell {
    NSString * _highlightedText;
    FLEXSystemLogMessage * _logMessage;
    NSAttributedString * _logMessageAttributedText;
    UILabel * _logMessageLabel;
}

@property (nonatomic, copy) NSString *highlightedText;
@property (nonatomic, retain) FLEXSystemLogMessage *logMessage;
@property (nonatomic, retain) NSAttributedString *logMessageAttributedText;
@property (nonatomic, retain) UILabel *logMessageLabel;

+ (id)attributedTextForLogMessage:(id)arg1 highlightedText:(id)arg2;
+ (id)displayedTextForLogMessage:(id)arg1;
+ (id)logTimeStringFromDate:(id)arg1;
+ (double)preferredHeightForLogMessage:(id)arg1 inWidth:(double)arg2;

- (void).cxx_destruct;
- (id)highlightedText;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (id)logMessage;
- (id)logMessageAttributedText;
- (id)logMessageLabel;
- (void)setHighlightedText:(id)arg1;
- (void)setLogMessage:(id)arg1;
- (void)setLogMessageAttributedText:(id)arg1;
- (void)setLogMessageLabel:(id)arg1;

@end
