/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXGlobalsEntry : NSObject <FLEXPatternMatching> {
    id /* block */  _entryNameFuture;
    id /* block */  _rowAction;
    id /* block */  _viewControllerFuture;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) id /* block */ entryNameFuture;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) id /* block */ rowAction;
@property (readonly) Class superclass;
@property (nonatomic, readonly) id /* block */ viewControllerFuture;

+ (id)entryWithEntry:(Class)arg1 row:(unsigned long long)arg2;
+ (id)entryWithNameFuture:(id /* block */)arg1 action:(id /* block */)arg2;
+ (id)entryWithNameFuture:(id /* block */)arg1 viewControllerFuture:(id /* block */)arg2;

- (void).cxx_destruct;
- (id /* block */)entryNameFuture;
- (bool)matches:(id)arg1;
- (id /* block */)rowAction;
- (id /* block */)viewControllerFuture;

@end
