/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXRuntimeUtility : NSObject

+ (id)appendName:(id)arg1 toType:(id)arg2;
+ (id)attributesDictionaryForProperty:(struct objc_property { }*)arg1;
+ (id)classHierarchyOfObject:(id)arg1;
+ (id)descriptionForIvarOrPropertyValue:(id)arg1;
+ (id)editableJSONStringForObject:(id)arg1;
+ (void)enumerateTypesInStructEncoding:(const char *)arg1 usingBlock:(id /* block */)arg2;
+ (unsigned long long)fieldNameOffsetForTypeEncoding:(const BOOL*)arg1;
+ (id)fullDescriptionForProperty:(struct objc_property { }*)arg1;
+ (bool)isReadonlyProperty:(struct objc_property { }*)arg1;
+ (bool)isTollFreeBridgedValue:(id)arg1 forCFType:(const char *)arg2;
+ (id)objectValueFromEditableJSONString:(id)arg1;
+ (id)performSelector:(SEL)arg1 onObject:(id)arg2 withArguments:(id)arg3 error:(id*)arg4;
+ (bool)pointerIsValidObjcObject:(const void*)arg1;
+ (id)potentiallyUnwrapBoxedPointer:(id)arg1 type:(const BOOL*)arg2;
+ (id)prettyArgumentComponentsForMethod:(struct objc_method { }*)arg1;
+ (id)prettyNameForIvar:(struct objc_ivar { }*)arg1;
+ (id)prettyNameForMethod:(struct objc_method { }*)arg1 isClassMethod:(bool)arg2;
+ (id)prettyNameForProperty:(struct objc_property { }*)arg1;
+ (id)readableTypeForEncoding:(id)arg1;
+ (BOOL*)returnTypeForMethod:(struct objc_method { }*)arg1;
+ (void)setValue:(id)arg1 forIvar:(struct objc_ivar { }*)arg2 onObject:(id)arg3;
+ (SEL)setterSelectorForProperty:(struct objc_property { }*)arg1;
+ (void)tryAddPropertyWithName:(const char *)arg1 attributes:(id)arg2 toClass:(Class)arg3;
+ (id)typeEncodingForProperty:(struct objc_property { }*)arg1;
+ (id)valueForIvar:(struct objc_ivar { }*)arg1 onObject:(id)arg2;
+ (id)valueForNumberWithObjCType:(const char *)arg1 fromInputString:(id)arg2;
+ (id)valueForPrimitivePointer:(void*)arg1 objCType:(const char *)arg2;
+ (id)valueForProperty:(struct objc_property { }*)arg1 onObject:(id)arg2;

@end
