/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXArgumentInputFontView : FLEXArgumentInputView {
    FLEXArgumentInputView * _fontNameInput;
    FLEXArgumentInputView * _pointSizeInput;
}

@property (nonatomic, retain) FLEXArgumentInputView *fontNameInput;
@property (nonatomic, retain) FLEXArgumentInputView *pointSizeInput;

+ (bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;
+ (double)verticalPaddingBetweenFields;

- (void).cxx_destruct;
- (id)fontNameInput;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;
- (id)inputValue;
- (bool)inputViewIsFirstResponder;
- (void)layoutSubviews;
- (id)pointSizeInput;
- (void)setBackgroundColor:(id)arg1;
- (void)setFontNameInput:(id)arg1;
- (void)setInputValue:(id)arg1;
- (void)setPointSizeInput:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
