/* Generated by RuntimeBrowser
   Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
 */

@interface FLEXColorComponentInputView : UIView {
    <FLEXColorComponentInputViewDelegate> * _delegate;
    UISlider * _slider;
    UILabel * _valueLabel;
}

@property (nonatomic) <FLEXColorComponentInputViewDelegate> *delegate;
@property (nonatomic, retain) UISlider *slider;
@property (nonatomic, retain) UILabel *valueLabel;

- (void).cxx_destruct;
- (id)delegate;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setSlider:(id)arg1;
- (void)setValueLabel:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)slider;
- (void)sliderChanged:(id)arg1;
- (void)updateValueLabel;
- (id)valueLabel;

@end
