/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDSourceOrderManager : NSObject {
    HDProfile * _profile;
    HDDatabaseValueCache * _sourceOrdersForTypeCache;
}

+ (id)_defaultOrderingWithSources:(id)arg1;

- (void).cxx_destruct;
- (bool)_addOrderedSource:(id)arg1 objectType:(id)arg2 transactionCache:(id)arg3 transaction:(id)arg4 error:(id*)arg5;
- (id)_defaultSourceCacheItemWithTransactionCache:(id)arg1 database:(id)arg2 error:(id*)arg3;
- (id)_fetchSourceCacheItemForObjectType:(id)arg1 transactionCache:(id)arg2 transaction:(id)arg3 error:(id*)arg4;
- (bool)_insertCodableObjectTypeSourceOrder:(id)arg1 transactionCache:(id)arg2 transaction:(id)arg3 error:(id*)arg4;
- (id)_mergedSourceOrderForExistingOrder:(id)arg1 incomingOrder:(id)arg2;
- (id)_orderedSourceIDsForOrderedSources:(id)arg1 sourcesByID:(id)arg2 objectType:(id)arg3 transactionCache:(id)arg4 database:(id)arg5 error:(id*)arg6;
- (id)_sourceCacheItemForObjectType:(id)arg1 error:(id*)arg2;
- (id)_sourceCacheItemForObjectType:(id)arg1 transactionCache:(id)arg2 transaction:(id)arg3 error:(id*)arg4;
- (id)_sourceOrderForCodableSourceOrder:(id)arg1 transactionCache:(id)arg2 transaction:(id)arg3 error:(id*)arg4;
- (bool)_updateOrderedSourceIDsForWrappedSource:(struct _HDWrappedSource { id x1; void x2; /* Warning: Unrecognized filer type: 'e' using 'void*' */ void*x3; BOOL x4; void*x5; out const void*x6; long x7; out in void*x8; void*x9; long x10; out in void*x11; void*x12; void*x13; short x14; void*x15; double x16; SEL x17; SEL x18; void*x19; void*x20; void*x21; SEL x22; SEL x23; void*x24; long x25; long x26; out BOOL x27; void*x28; void*x29; out const void*x30; long x31; out in void*x32; void*x33; long x34; out in void*x35; void*x36; void*x37; void*x38; void*x39; long long *x40; long long *x41; struct __compressed_pair<long long *, std::__1::allocator<long long> > { long long *x_42_1_1; } x42; }*)arg1 transactionCache:(id)arg2 transaction:(id)arg3 error:(id*)arg4;
- (bool)_updateSourceOrder:(id)arg1 type:(id)arg2 error:(id*)arg3;
- (bool)_updateSourceOrder:(id)arg1 type:(id)arg2 transactionCache:(id)arg3 transaction:(id)arg4 error:(id*)arg5;
- (bool)addOrderedSource:(id)arg1 objectTypes:(id)arg2 error:(id*)arg3;
- (bool)createSourceOrdersWithCodables:(id)arg1 error:(id*)arg2;
- (id)initWithProfile:(id)arg1;
- (id)orderedSourceIDsForObjectType:(id)arg1 bundleIdentifierMapping:(id)arg2 userOrdered:(bool*)arg3 error:(id*)arg4;
- (id)orderedSourcesForObjectType:(id)arg1 error:(id*)arg2;
- (void)resetCacheInDatabase:(id)arg1;
- (bool)resetCacheWithError:(id*)arg1;
- (bool)updateOrderedSources:(id)arg1 forObjectType:(id)arg2 error:(id*)arg3;

@end
