/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRE.framework/CoreRE
 */

@interface REAudioManagerNotificationListener : NSObject {
    struct AudioManager_AVAudioEngine { int (**x1)(); id x2; /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x3; in out const double x4; void*x5; const void*x6; double x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; in short x14; int x15; void*x16; in void*x17; double x18; void*x19; long x20; out in void*x21; void*x22; long x23; out in void*x24; void*x25; void*x26; short x27; void*x28; double x29; SEL x30; SEL x31; void*x32; void*x33; void*x34; SEL x35; SEL x36; void*x37; in out const double x38; void*x39; const void*x40; double x41; void*x42; void*x43; void*x44; void*x45; void*x46; void*x47; in short x48; int x49; void*x50; in void*x51; double x52; void*x53; long x54; out in void*x55; void*x56; long x57; out in void*x58; void*x59; void*x60; const void*x61; SEL x62; SEL x63; void*x64; double x65; int x66; out void*x67; int x68; void*x69; void*x70; const out void*x71; void*x72; unsigned short x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; short x80; void*x81; double x82; SEL x83; SEL x84; void*x85; void*x86; } * _owner;
}

- (void)engineInterrupted:(id)arg1;
- (id)initWithOwner:(void*)arg1;
- (void)sessionInterrupted:(id)arg1;

@end
