/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreServices.framework/CoreServices
 */

@interface _LSBindingForLog : NSObject {
    /* Warning: unhandled struct encoding: '{LSBinding="bundle"I"bundleData"^{LSBundleData}"claim"I"claimData"^{?}"userInfo"@"reason"@"NSString"}' */ struct LSBinding { 
        unsigned int bundle; 
        struct LSBundleData {} *bundleData; 
        unsigned int claim; 
        struct { /* ? */ } *claimData; 
        id userInfo; 
    }  _binding;
    _LSDatabase * _db;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
- (id)initWithState:(const struct State { struct LSContext {} *x1; struct BindingEvaluator { id x_2_1_1; id x_2_1_2; id x_2_1_3; unsigned long x_2_1_4; unsigned short x_2_1_5; oneway /* Warning: Unrecognized filer type: 'e' using 'void*' */ void*x_2_1_6; const short x_2_1_7; int x_2_1_8; out in inout void*x_2_1_9; void*x_2_1_10; unsigned int x_2_1_11/* : ? */; void*x_2_1_12; const void*x_2_1_13; unsigned char x_2_1_14[32]; } x2; bool x3; unsigned long long x4; unsigned int x5; unsigned int x6; struct vector<LSBundleClass, std::__1::allocator<LSBundleClass> > { unsigned int *x_7_1_1; unsigned int *x_7_1_2; struct __compressed_pair<LSBundleClass *, std::__1::allocator<LSBundleClass> > { unsigned int *x_3_2_1; } x_7_1_3; } x7; id /* block */ x8; id x9; void*x10; id x11; struct vector<LaunchServices::BindingEvaluation::ExtendedBinding, std::__1::allocator<LaunchServices::BindingEvaluation::ExtendedBinding> > { struct ExtendedBinding {} *x_12_1_1; struct ExtendedBinding {} *x_12_1_2; struct __compressed_pair<LaunchServices::BindingEvaluation::ExtendedBinding *, std::__1::allocator<LaunchServices::BindingEvaluation::ExtendedBinding> > { struct ExtendedBinding {} *x_3_2_1; } x_12_1_3; } x12; }*)arg1 binding:(const struct ExtendedBinding { unsigned int x1; struct LSBundleData {} *x2; unsigned int x3; struct { /* ? */ } *x4; id x5; bool x6; bool x7; id x8; BOOL x9; id x10; out /* Warning: Unrecognized filer type: 'p' using 'void*' */ void*x11; void*x12; int x13; out in void*x14; long x15; void*x16; unsigned int x17/* : ? */; out out long x18; void*x19; void*x20; union { BOOL x_21_1_1; bool x_21_1_2; } x21; bool x22; }*)arg2;
- (id)redactedDescription;

@end
