/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContextKit.framework/ContextKit
 */

@interface CKContextSemaphore : NSObject <NSSecureCoding> {
    unsigned int  _sema;
    bool  _semaOwner;
    struct { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; int x5; unsigned int x6; unsigned long long x7; unsigned int x8; unsigned int x9; } * _shm;
    NSObject<OS_xpc_object> * _shmObject;
    unsigned long long  _shmSize;
}

+ (void)initialize;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned long long)activeGauge;
- (bool)busy;
- (void)dealloc;
- (void)decPending;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)gauge;
- (void)incPending;
- (id)initSemaphoreForXPCService;
- (id)initWithCoder:(id)arg1;
- (void)notify;
- (void)notifyAll;
- (unsigned long long)numAcquired;
- (long long)pending;
- (unsigned long long)pendingExceptionsCount;
- (unsigned long long)requestsServed;
- (void)resetPending;
- (void)setActiveGauge:(unsigned long long)arg1;
- (unsigned long long)sharedMemorySize;
- (bool)tryAcquire;
- (long long)waitFor:(double)arg1;

@end
