/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNSiriIntelligenceSettings : NSObject <CNSiriIntelligenceSettingsProtocol> {
    int  _notificationToken;
    bool  _shouldShowSiriSuggestions;
}

- (void)dealloc;
- (id)init;
- (void)setShouldShowSiriSuggestions:(bool)arg1;
- (bool)shouldShowSiriSuggestions;

@end
