/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNAtomicUnsignedIntegerGenerator : NSObject {
    long long  _n;
}

- (id)init;
- (unsigned long long)nextUnsignedInteger;

@end
